### ISSUE TITLE
Extract Option - JavaScript inside HTML

### ISSUE THREAD

**Issue by git-testing** [AtomLinter/linter-jshint#106]
I just started using Atom - coming from Sublime. I installed linter-jshint and jshint

After setting the jshint executable path. I had jshint working on JavaScript files. However, after several hours I still cannot get it to work with JavaScript in HTML files. I looked in package.json and the docs but did not find something that works.

I saw that there is a flag --extract=[auto|always|never]. But I am not sure how to use it in Atom.

Are there any other solutions? Workarounds?

**Comment by StatelessCat** [comment]
Hey,
I had the same issue as you.

Because of https://github.com/AtomLinter/linter-jshint/pull/46 , by default `linter-jshint` no longer lint js inside html file.

The workaround I uses is to edit `~/.atom/packages/linter-jshint/lib/main.coffee` and to replace : 

```
grammarScopes: ['source.js', 'source.js.jsx']
```

by

```
grammarScopes: ['source.js', 'source.js.jsx', 'text.html.basic']
```

**Comment by steelbrain** [comment]
I would love to review a PR for this.

**Comment by StatelessCat** [comment]
I would love to see or do a PR for this.
But I need to be sure if https://github.com/AtomLinter/linter-jshint/pull/46 is related to upstream `jshint` and if Issues https://github.com/AtomLinter/linter-jshint/issues/21 and https://github.com/AtomLinter/linter-jshint/issues/20 will not show again.

**Comment by steelbrain** [comment]
Ah right, The best way to achieve it would be behind a config then.

**Comment by Arcanemagus** [comment]
Assuming these scopes are the Atom scopes, is there any reason this shouldn't just include `source.js.embedded.html`?

**Comment by StatelessCat** [comment]
That seems really cool, will soon try the new feature or wait 1.0.6 releases.
Thanks guys !
