### ISSUE TITLE
Option to disable linting whilst typing

### ISSUE THREAD

**Issue by bradleyflood** [AtomLinter/linter-jshint#107]
Error messages popping up about errors in the code I haven't even finished typing, whilst I'm in the middle of typing it, is quite annoying. Can you set a delay so the linting only happens after a second or two?
And have this as a configurable option?

**Comment by jazzpi** [comment]
In the Linter package itself there is the option "Lint on fly". If you disable that option, your files will only get linted when saved.

**Comment by bradleyflood** [comment]
Thanks. Where do you find this information? I was unable to find any such info on either of the packages or repos.

**Comment by jazzpi** [comment]
I thought I saw an option like that, so I looked at the options of `linter-jshint` and `linter` and there it was :wink:

**Comment by iam4x** [comment]
@jazzpi answer is right, you have to go on `Linter` package preferences and not `linter-jshint`

**Comment by chrishiestand** [comment]
This isn't an obvious step to the end-user. Perhaps we should add a sentence to the linter-jshint preferences pointing (even better, linking if possible) to the linter preferences?

**Comment by steelbrain** [comment]
@chrishiestand sorry if it took your time, but by nature `linter` is the base and `linter-jshint` is a provider. I think it's quite obvious that some of the global linting settings will be present there :)

**Comment by chrishiestand** [comment]
@steelbrain I think it's only obvious in retrospect. A user who is new to Atom and installs linter-jshint first will not necessarily know this. Even if the user knows this package hierarchy it is not obvious which settings should live in linter and which might be set or overridden by linter-jshint.

I think there's a strong UI case to be made for making preference navigation easy for the user. So even if the information is redundant, it's nice to have it on common paths a user travels.

It's relatively minor, I won't belabor the point further.

**Comment by bradleyflood** [comment]
Agreed. My two cents as well -- In my experience this isn't clear. I found that neither of the repos mention clearly how to edit the additional settings that aren't displayed in the Atom settings dialog. I couldn't figure this out easily myself. I'm an experienced front end dev and consider myself technically minded but it wasn't clear.
Cheers guys.
