### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by Eschon** [AtomLinter/linter-jshint#111]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (/Users/egon/.atom/packages/linter/lib/main.coffee:57:8)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
```

**Comment by jonnitto** [comment]
+1

**Comment by iam4x** [comment]
@steelbrain Said on slack is going to address this one

**Comment by stramel** [comment]
I ran into this issue as well. :+1:

**Comment by none-da** [comment]
:+1:

**Comment by steelbrain** [comment]
The work is happening here people https://github.com/AtomLinter/linter-jshint/pull/103

**Comment by opponitur** [comment]
+1

**Comment by steelbrain** [comment]
@opponitur it's actually fixed, you might wanna upgrade your linter-jshint.

**Comment by batjko** [comment]
Still getting this though:
![image](https://cloud.githubusercontent.com/assets/7287076/8615685/c6a538e8-26ec-11e5-89a5-2ff83a155e56.png)

![image](https://cloud.githubusercontent.com/assets/7287076/8615691/d428ec44-26ec-11e5-9840-b34f2fdc9a12.png)

**Comment by steelbrain** [comment]
@batjko that's super-weird.
You might wanna try
```
mv ~/.atom ~/.atom-bkp
apm install linter
apm install linter-jshint
```
and then see if it fixes the problem

**Comment by batjko** [comment]
Well, I'd like to avoid renaming my .atom folder, lots of stuff in there I don't want to have to do again.

But I will try and re-install Linter and linter-jshint, let's see if that does the trick.

**Comment by Eschon** [comment]
@steelbrain Did that recently because of my problems in [Linter/#650](https://github.com/AtomLinter/Linter/issues/650) and still get the same deprecation error

**Comment by steelbrain** [comment]
The file produces that error doesn't even exist :P

**Comment by Eschon** [comment]
When I click on the file names in the Deprecation cop it opens a file for me so at least it exists in my `linter-jshint` installation.

**Comment by steelbrain** [comment]
Which file does it open? `main.coffee`?

**Comment by batjko** [comment]
@steelbrain The error points at the main.coffee of the Linter package, not the linter-jshint package.

https://github.com/AtomLinter/Linter/blob/master/lib/main.coffee#L57

**Comment by batjko** [comment]
Also I am getting the same issue for some of the other linter-xxx sub-packages.
Looks like the deprecation is actually on the Linter itself.

**Comment by steelbrain** [comment]
What if I told you that the file it's requiring doesn't even exist, can someone post ls results of
```
ls ~/.atom/packages/linter-jshint/lib
```

**Comment by batjko** [comment]
@steelbrain Check my comment above.

**Comment by steelbrain** [comment]
I actually wrote the code there that's reporting the deprecations :sweat_smile: 
There's no deprecation in linter itself, but it reports whenever it tries to require a package like the legacy API.

**Comment by Eschon** [comment]
`ls ~/.atom/packages/linter-jshint/lib` gives me `init.coffee` and `linter-jshint.coffe`
But as @batjko said the first line of the deprecation warning points to `~/.atom/packages/linter/lib/main.coffee` not `~/.atom/packages/linter-jshint/lib/main.coffee`

**Comment by steelbrain** [comment]
I can't believe I did this Hahaha, I had upgraded this package to the latest API but haven't published a release yet. :facepalm:

**Comment by steelbrain** [comment]
Just pushed a release people, Enjoy.

**Comment by Eschon** [comment]
Well we're all humans :laughing: 
Deprecation is gone now.
