### ISSUE TITLE
Missing source file causes "jshint not found" error

### ISSUE THREAD

**Issue by BlaM** [AtomLinter/linter-jshint#113]
How to reproduce the error:

- have linter-jshint active
- in Atom have a project open
- create a new directory and then a js file within that directory
- open the file in the editor and write some code.
- close Atom - have the file still open at that moment
- delete the new directory
- reopen Atom, which will reopen the last project and (at least attempt to) reopen the now missing file
- *BOOM*

![image](https://cloud.githubusercontent.com/assets/176011/8591528/314c135c-2629-11e5-8748-3d477039d368.png)

Error message says that the linter binary/node is missing - while actually it is the source code file that is not there.

Very confusing if you now try to figure out why Atom cannot find the linter while you can.

**Comment by steelbrain** [comment]
Yep, the linters using the legacy API don't provide much info, it's been fixed by the rewrite.
