### ISSUE TITLE
Warnings are errors since 1.0.0

### ISSUE THREAD

**Issue by yoctozepto** [AtomLinter/linter-jshint#119]
Pre 1.0.0 warnings were reported as warnings, now everything is an error, e.g. a missing semicolon.

**Comment by steelbrain** [comment]
We are actually using JSHint's `error.id.substr(1, error.id.length - 2)` to extract id, it gives us something like `(error)` in input.
if you can suggest us how to identify a warning using the json reporter under the npm name `jshint-json`. It should speed up the resolution process.

**Comment by yoctozepto** [comment]
If `error.code` starts with: 
* `E` - it is an error,
* `W` - it is a warning,
* `I` - it is an info.

Take a peek here:
https://github.com/jshint/jshint/blob/06b57649414e44a9df6a46907f3ac93513e44221/src/messages.js

I guess the linter worked like this pre 1.0.0.

**Comment by steelbrain** [comment]
Aaha! Thanks, gonna fix ASAP

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-jshint/commit/163d14cc3cd82e39b96772997084aedfcdd61fd4
