### ISSUE TITLE
Catch JSON errors issue

### ISSUE THREAD

**Issue by alexbeletsky** [AtomLinter/linter-jshint#120]
There is [such commit](https://github.com/AtomLinter/linter-jshint/commit/0fb21947faa437c55f54fb15ca05c6d404a126e6) for handling parsing errors, it makes total sense, but after upgrade it put my Atom in a mess.

While I open any `.js` file, I see error notification "Invalid Result recieved from JSHint".

The reason is `JSON.parse()` is not able to handle empty strings and throws an exception. I'm not sure, but maybe `jshint` previosly returned `{}` or `[]`, but not it's just empty `""`. 

There should be a check for empty string and if so, skip the rest of processing. If you are fine with that I can submit a PR.

PS. there is a typo in `recieved` => `received`.. I'm always doing that mistake, as well :)

**Comment by steelbrain** [comment]
Yep, this is a known bug on OSX that `child_process.spawn` of node returns empty when you run it from applications, run it from CLI to make it work

**Comment by alexbeletsky** [comment]
sorry, what do you mean "run it from CLI to make it work"?

**Comment by steelbrain** [comment]
```
atom /path/to/folder
```

**Comment by alexbeletsky** [comment]
that helps, indeed.. but doesn't sound like a solution. Could be the reason that `child_process.spawn` requires a `cwd` or anything else is missing?

**Comment by steelbrain** [comment]
could you hard-code a cwd and report if it works? :)

**Comment by wmccracken** [comment]
I'm seeing this same error. It goes away if I run from the command line but then is seems the jsxhint is broken.

**Comment by alexbeletsky** [comment]
@steelbrain tried and it works fine with `cmd` being set, is there any way we can get `cmd` from atom object, perhaps (I'm not very familiar with internals)

**Comment by alexbeletsky** [comment]
@steelbrain sorry, was to fast. nope, `cmd` set seems not helping.

**Comment by stdavis** [comment]
I'm getting the same error message as well on OSX. I agree with @alexbeletsky that opening from the command line isn't a great solution. I'd be happy to help test proposed solutions.

**Comment by steelbrain** [comment]
can you guys post the contents of `process.env.PATH` from dev tools?

**Comment by stdavis** [comment]
![image](https://cloud.githubusercontent.com/assets/1326248/8624953/d21db4b4-26f8-11e5-9fa0-08676de971dd.png)

**Comment by steelbrain** [comment]
now what's the contents of `$PATH` in your terminal?

**Comment by stdavis** [comment]
![image](https://cloud.githubusercontent.com/assets/1326248/8625000/14ca9282-26f9-11e5-8104-09128d19cb76.png)

**Comment by steelbrain** [comment]
Now that's what the problem is :D
Moved to https://github.com/AtomLinter/Linter/issues/726
