### ISSUE TITLE
"Invalid Result Received From JSHint"

### ISSUE THREAD

**Issue by adarhef** [AtomLinter/linter-jshint#122]
"Please check your console for more info". I don't know which console it's referring to so I have no idea what's going on...

The linter doesn't work and spits this message out every time it attempts to lint. Strangely, when launching Atom from CL it works just fine.

I thought it might be that the path to JSHint isn't configured, so I pasted the output of "which jshint" into the 'JSHint executable path' setting, to no avail. 

I'm on the latest 1.0.4 version. Any ideas what this could be about? 

P.S - I'd attach an image but I'm on OS X El Capitan's public beta and for some reason when I try taking a screenshot of Atom I end up getting a plain black image.

**Comment by steelbrain** [comment]
It should be your developer console. See https://github.com/AtomLinter/linter-jshint/issues/117
and https://github.com/AtomLinter/Linter/issues/726

**Comment by juanpasolano** [comment]
:+1: 
And launching from CL fixes it. jmm?
Also using 1.0.4
