### ISSUE TITLE
The bubble notification does not appear

### ISSUE THREAD

**Issue by rldona** [AtomLinter/linter-jshint#125]
Hi,

I started to work with Atom in version 1.0.2 on Mac OS X (10.10.4).

I have installed linter and linter-jshint packages with the default settings, but whenever you save a file (which lacks a semicolon, for example) I get the following error:

![captura de pantalla 2015-07-11 a las 20 16 03](https://cloud.githubusercontent.com/assets/1206870/8634837/aee1f066-2809-11e5-90ef-937d7b5f1277.png)

The bubble notification does not appear.

Do I have to perform some additional configuration?

Thanks !!

**Comment by steelbrain** [comment]
It's a known OSX bug. See AtomLinter/Linter#726

**Comment by steelbrain** [comment]
or maybe just have a look at your devloper-tools' consume. CTRL + SHIFT + I on linux.

**Comment by rldona** [comment]
Or maybe the package does not work well ...

**Comment by steelbrain** [comment]
The other package doesn't really handle it itself, It's a io.js and chromium issue.
