### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by chodorowicz** [AtomLinter/linter-jshint#126]
Any idea? Running 1.0.4 and Atom 1.0.2
![image](https://cloud.githubusercontent.com/assets/119451/8637446/2ed8122c-2892-11e5-8ba8-b3ad6f4cee6f.png)

**Comment by steelbrain** [comment]
It's a known OSX bug. See AtomLinter/Linter#726

**Comment by chodorowicz** [comment]
Ok, thanks. Modifying Atom init script worked for me.
