### ISSUE TITLE
Check Console Error after 1.0.4 upgrade

### ISSUE THREAD

**Issue by leobauza** [AtomLinter/linter-jshint#128]
I get:

> Invalid Result recieved from JSHint: Check your console for more info

When I check my console I see:

>JSHint Result:

Everything worked fine before the bunch of quick updates that happened last week to get rid of the deprecation (I am assuming thats what they were for).

Thanks

**Comment by steelbrain** [comment]
It's a known bug on OSX, see https://github.com/AtomLinter/Linter/issues/726
