### ISSUE TITLE
Error pop ups, after 1.0.4 update

### ISSUE THREAD

**Issue by leofle** [AtomLinter/linter-jshint#129]
Constant error popups appearing on screen, for no reason.

![screenshot 2015-07-12 23 19 33](https://cloud.githubusercontent.com/assets/2674606/8639822/546eedb6-28ed-11e5-8c19-91e995114e09.JPG)

**Comment by steelbrain** [comment]
It's a known bug on OSX, see https://github.com/AtomLinter/Linter/issues/726
