### ISSUE TITLE
Invalid result received from JSHint

### ISSUE THREAD

**Issue by Eschon** [AtomLinter/linter-jshint#130]
My problem is similar to #128 or #124 however I don't think it is related to https://github.com/AtomLinter/Linter/issues/726 because I always run atom from the command line and it worked fine a few days ago on linter-jshint 1.0.2 or 1.0.3 (not sure which version i had before updating to 1.0.4). 

Since updating today it stopped working but rolling back to 1.0.2 or 1.0.3 doesn't seem to fix the issue.
I'm running OS X 10.10.4 and Atom 1.0.2

**Comment by xpol** [comment]
Yes I have this issue too..

**Comment by steelbrain** [comment]
`1.0.4` doesn't really do anything new, it just reports it via notification while the other versions suppress it, if you are having an empty response in the console, then it's very much related to the issue you mentioned above.

**Comment by Eschon** [comment]
Yeah I get an empty response but Atom should have no problem with my path since I always start it from the command line. I also don't think that it is a problem with `1.0.4` because rolling back to an older version doesn't fix the problem.

**Comment by steelbrain** [comment]
What's your jshint exact path? and what are the contents of `process.env.PATH`?

**Comment by Eschon** [comment]
JSHint path: `/Users/egon/.nvm/versions/node/v0.12.4/bin/jshint`
How do I get `process.env.PATH`?

Anyways I just updated to `1.0.5` and now it works again.

**Comment by steelbrain** [comment]
Open dev tools and write `process.env.PATH` in the console and You'll get the value. and Wow :smiley:

**Comment by Eschon** [comment]
Ok `process.env.PATH` gives me `/Users/egon/.nvm/versions/node/v0.12.4/bin:/Users/egon/.rvm/gems/ruby-2.1.5/bin:/Users/egon/.rvm/gems/ruby-2.1.5@global/bin:/Users/egon/.rvm/rubies/ruby-2.1.5/bin:/Users/egon/bin/android-sdk-macosx/tools:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/egon/.rvm/bin`

**Comment by steelbrain** [comment]
That nvm dir doesn't seem to be listed in there. Weird.

**Comment by steelbrain** [comment]
Closing as the update fixed it for You.

**Comment by Eschon** [comment]
> That nvm dir doesn't seem to be listed in there. Weird.

Isn't it the first one?

**Comment by steelbrain** [comment]
Ah, right, I feel like I should get some sleep :sweat_smile:

**Comment by openroc** [comment]
this bug wasn't fixed in atom 1.0.2, and linter-jshint 1.0.5

**Comment by steelbrain** [comment]
@openroc Your problem is different than theirs, in the 1.0.x increments, I just added an error notification and tweak it, nothing changed functionally. Also it's a known bug with the way OSX handles env variables, not with this package :)

**Comment by openroc** [comment]
@steelbrain thanks, the problem was fixed after updating to v1.1.2. :)
