### ISSUE TITLE
Bring back disableWhenNoJshintrcFileInPath

### ISSUE THREAD

**Issue by bluedaniel** [AtomLinter/linter-jshint#135]
There used to be an option to disable this plugin if there was no jshintrc, why was this taken out?

**Comment by steelbrain** [comment]
Because we are no longer looking for `.jshintrc` ourselves, we're passing the path to `jshint` cli and leave everything else to it, does it support this kinda parameter?

**Comment by bluedaniel** [comment]
Not that I can see. From the docs it says that without any inputs (.jshintrc, package.json.jshintConfig, etc) then: 

`If this search yields no results, jshint will lint the input code as if no linting rules had been enabled.` - http://jshint.com/docs/cli/#specifying-input

**Comment by steelbrain** [comment]
Moved to https://github.com/atom-community/linter/issues/744
