### ISSUE TITLE
Linting code inside markdown file

### ISSUE THREAD

**Issue by li-xinyang** [AtomLinter/linter-jshint#136]
After I add the .jshintignore file both in the project directory and home directory. It still lints the JavaScripe code inside the .md file.

How to set the package to ignore certain file type?

![screen shot 2015-07-17 at 3 52 17 pm](https://cloud.githubusercontent.com/assets/3349406/8743334/5c6eaefa-2ca0-11e5-8d38-dd4fee4619f2.png)

**Comment by steelbrain** [comment]
Just pushed a new release, We have a present for you in `linter-jshint` configuration :wink:

**Comment by ksmithut** [comment]
@steelbrain I'm still having an issue with this. I see the two options `lintInlineJavaScript` and `disableWhenNoJshintrcFileInPath`, and both of them are set to false. The problem I'm having is that I have a README.md file in my project folder (which has javascript code blocks) and a `.jshintrc` for my project, which is needed for linting the rest of the project files.

I'm not sure how the linter works, but is there a way to only lint the code in the code blocks?

**Comment by iam4x** [comment]
@ksmithut I will open an issue on main linter.
