### ISSUE TITLE
[Feature] disable linter-jshint for specific files, or on demand (without restarting Atom)

### ISSUE THREAD

**Issue by StatelessCat** [AtomLinter/linter-jshint#138]
Hey,
I love `linter-jshint` but when I work on project that generate a lot of error, i want to disable linter-jshint for specific files (because too many flood on the bottom window).
Is it possible ?
Or is it possible to hide the windows that is showing all linting errors ?
Is it also possible to disable linter-jshint without restarting Atom ? 
Thanks

**Comment by Arcanemagus** [comment]
Have you tried hitting `Ctrl` + `Alt` + `P` (Or your specific OS's method of opening the command pallette), typing `linter` and selecting the `Linter: Toggle` option?

Note that when you close and re-open the file the linter will be re-enabled.

**Comment by Luminess** [comment]
Maybe having a comment at the top that will disable linting for the file if found.

**Comment by steelbrain** [comment]
@Luminess we don't really read the whole file, we just pass it as is to jshint, also as @Arcanemagus suggested, the core linter provides `linter:toggle` command, You can map it on your key of choice and enable/disable linting per editor with ease.

**Comment by steelbrain** [comment]
Closing, but feel free to continue the discussion

**Comment by StatelessCat** [comment]
Thanks for the workaround. ```linter:TogglePanel``` can be usefull, I'll look later if it's hard to write a PR to add a checkbox in settings for disabling this panel by default.
