### ISSUE TITLE
Save file inside script blocks trigers lint inline JavaScript

### ISSUE THREAD

**Issue by li-xinyang** [AtomLinter/linter-jshint#149]
I left the option `Lint Inline JavaScript` unchecked in my **linter-jshint** settings and the linter won't lint any inline script as expected. 

However, when I save the file while the cusor inside the script block it will start to lint the code inside the file.

![screen shot 2015-07-22 at 3 01 52 pm](https://cloud.githubusercontent.com/assets/3349406/8819852/a579c72a-3082-11e5-8c83-a1612f3a7427.png)
![screen shot 2015-07-22 at 3 02 06 pm](https://cloud.githubusercontent.com/assets/3349406/8819851/a578a868-3082-11e5-8f98-ce3637b70808.png)

**Comment by steelbrain** [comment]
Yep, that's because Linter gets the scope of the file using the current cursor position and when you have selected a position like that, Atom gives it a a scopes array with `source.js` in it and it lints according to that, not sure if it's a bug or feature, but it's like that by design.

**Comment by li-xinyang** [comment]
Okay, thank you for your quick response. :beers:
