### ISSUE TITLE
Sync issues when same file is opened in multiple panes

### ISSUE THREAD

**Issue by mjomble** [AtomLinter/linter-jshint#152]
I'm not sure if this is an issue with the base linter or linter-jshint, but if you open the same file in two panes, some issues start appearing that seem to be related to syncing the linter state between the panes.

For example, if "Lint on fly" is disabled and there's a JSHint warning in the file and you fix it in one pane, the code changes automatically sync to the other pane as well so the cause of the warning is gone, but the warning itself still remains. It only goes away if I edit something in the other pane and save it.

If you're unable to reproduce the issue, I can post a more detailed example.

**Comment by piotr-cz** [comment]
Confirming the issue.
When file is opened in to panes, Issues at the bottom of screen update only when I change the code in the pane that was opened first. When I'm making edits in second pane, issues are re-appended.

**Comment by steelbrain** [comment]
Closing in favor of https://github.com/atom-community/linter/issues/871
