### ISSUE TITLE
eslint conflict

### ISSUE THREAD

**Issue by Mech7** [AtomLinter/linter-jshint#154]
When i check out this repo: https://github.com/erikras/react-redux-universal-hot-example
I get warnings from jshin while there is no .jshintrc file only a .eshint but still it gives warning from jshint i need to disable it because it throws many warnings that esnext needs to be set to true.

I think it should not trigger anything if there is no config file.

**Comment by steelbrain** [comment]
Yep, that's a choice that we made, it's because we are no longer searching for `.jshintrc` ourselves because it can be on so many locations, maybe even in `package.json` of it.
Here's the alternative way https://github.com/atom-community/linter/issues/744
