### ISSUE TITLE
Throwing a unnecessary semi-colon error, but code needs semi-colon.

### ISSUE THREAD

**Issue by Heasummn** [AtomLinter/linter-jshint#155]
At the end of a function, you should be placing a semi-colon, but the jshint is throwing an error. The code stops working if I take away the semi-colon.

**Comment by steelbrain** [comment]
That's actually a jshint thing, not a linter-jshint thing.

**Comment by iam4x** [comment]
@Heasummn http://jshint.com/docs/options/#asi
