### ISSUE TITLE
.jshintignore not respected

### ISSUE THREAD

**Issue by AgentME** [AtomLinter/linter-jshint#156]
I put a `.jshintignore` file with the contents of `**` to make it ignore the directory. I've opened atom in that directory and opened a file in it, but it's still linting the file. Running `jshint` on the file in a terminal respects the `.jshintignore` file correctly.

**Comment by steelbrain** [comment]
We actually invoke jshint with no special thing. Not sure what the problem is.

**Comment by AgentME** [comment]
Oh, I think this might actually be a jshint bug. If I run jshint from a different directory, then the `.jshintignore` file inside my program's directory isn't respected (but the `.jshintrc` file in that directory is respected). I'll report that there.
