### ISSUE TITLE
plugin no longer seems to respect local .jshintrc

### ISSUE THREAD

**Issue by keirlawson** [AtomLinter/linter-jshint#157]
Using Atom 1.03 this plugin seems to ignore settings (such as node: true) in my local .jshintrc.  I have disable when no jshintrc in path enabled in case that setting is something to do with this.

**Comment by steelbrain** [comment]
I am unable to reproduce this, can you try this and see if it works for you
```
cd ~/.atom/packages/linter-jshint
npm install atom-linter@latest
```

**Comment by keirlawson** [comment]
Weird, that seems to fix the issue for me...

**Comment by steelbrain** [comment]
Apm cache issue then.
