### ISSUE TITLE
Crash when typing typeof

### ISSUE THREAD

**Issue by ricardograca** [AtomLinter/linter-jshint#158]
Whenever I type `typeof` the following error shows up. After that happens just moving the cursor around, or typing anything anywhere else in the file will also trigger the error. If I finish writing the `typeof` statement (e.g. `if (typeof myVar === 'string') {}`), delete it, or comment it out, the error isn't shown any more.

```
/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5521 throw err; ^ TypeError: Cannot read property 'identifier' of undefined at Object.nud (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:2396:10) at expression (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34) at Object.fud (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3873:16) at expression (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:885:32) at statement (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1635:9) at statements (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1678:16) at block (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1797:13) at doFunction (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3103:5) at Object.nud (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3852:14) at expression (/home/ricardo/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34)
```

**Comment by Arcanemagus** [comment]
Btw if you wrap a block of code in ``` marks it can span multiple lines, makes viewing traces a _lot_ easier :wink:.

**Comment by ricardograca** [comment]
@Arcanemagus I did wrap it in backticks... :| Not my fault that Atom outputs errors in a single line.

**Comment by BlaM** [comment]
Not sure if that't the same bug, but each time I type "typeof" I get a red error popup telling me...

    Error Executing JSHint executable
    It's a known bug on OSX. See https://github.com/AtomLinter/Linter/issues/726

I can't see a message in the console and I'm using Windows 7 x64, not OSX.


ref: https://github.com/AtomLinter/Linter/issues/726

**Comment by ricardograca** [comment]
@BlaM I'm also seeing that error message now, and I'm using Ubuntu 15.04, not OSX as well.

**Comment by steelbrain** [comment]
That message shows up when you haven't specified path to a valid jshint executable.

**Comment by BlaM** [comment]
But linting works all the time unless there is a "typeof" without anything after it.

**Comment by BlaM** [comment]
So how do I get it to work on Windows? There is no "windows executable" file - just a javascript file at the location linter-jshint defaults to.

    require("../src/cli.js").interpret(process.argv);

- It works (and lints) most of the time - just explodes when I type "typeof".
- Crash happens on Windows 7 x64 and Windows 8 x64

Is there a way to disable the error message? It resumes to lint after I add something after that "typeof" - it's just annoying to get rid of that popup every time.

BTW: to be a bit more exact about when the error occurs:

* type "if ("
* Atom will add ")" and position the cursor between the opening and closing bracket
* Option 1:
  * type "typeof"
  * **crash**
* Option 2:
  * press 'delete' to remove closing bracket
  * type "typeof"
  * **no problem** - just can go on as expected.

**Comment by ricardograca** [comment]
Something tells me that generic "Error Executing JSHint executable" eats some unrelated errors, so you don't really know what the problem is. See my first comment for the actual message that appeared before an upgrade started showing only the generic message.

**Comment by BlaM** [comment]
For a start I got rid of line 58 in main.coffee. At least it won't bother me anymore. I can live with the fact that it won't lint if I have "if (typeof)" in my code.

**Comment by steelbrain** [comment]
I am super-busy with my work these days and would welcome a PR that replaces the error message and `console.log`s some debug info.

**Comment by BlaM** [comment]
My CoffeeScript knowledge may be enough to remove that line - but aside from that... Not my language. Too unreadable.

**Comment by ricardograca** [comment]
@steelbrain Is it possible to get the error message or stack trace from that `helpers.execNode()` call? I'm not familiar with the Atom API or CoffeeScript, but I can at least try to get a more precise error message.

**Comment by steelbrain** [comment]
@ricardograca I have a few free hours and will be doing that now.
