### ISSUE TITLE
No optional enable

### ISSUE THREAD

**Issue by peteyy** [AtomLinter/linter-jshint#161]
Working on multiple projects with either ESLint or JSHint can be a pain with this addon, I have to turn it on and off every time I switch projects.

The https://atom.io/packages/linter-eslint package has an option to turn it on only when .eslintrc is present in the project.
It would be nice to have in this package too.

Please add the settings to the GUI

**Comment by Ozonid** [comment]
:+1: +1

**Comment by keirlawson** [comment]
This option does exit? "Disable when to Jshintrc file in path"?

**Comment by steelbrain** [comment]
Guys, we need your suggestions to allow users to use a nicer way to enable/disable linters. See https://github.com/atom-community/linter/issues/744

**Comment by okonomiyaki3000** [comment]
You can use [project-manager](https://atom.io/packages/project-manager) to do this.

**Comment by mik01aj** [comment]
I can confirm that this **doesn't** work. I have this option selected:

![image](https://cloud.githubusercontent.com/assets/3027415/9635877/cbfb8424-5198-11e5-870a-a028983f13b5.png)

And my project root doesn't contain an `.jshintrc`, but `linter-jshint` still runs on both `*.js` and `*.jsx` files.

(This is a problem for me as some of my projects use `jshint`, and some use `eslint`.)

**Comment by keirlawson** [comment]
I've found I have this issue when I have one project with a jshintrc open in one atom window and one without in the other, it seems the linter is switched on or off atom-wide rather than per window

**Comment by mik01aj** [comment]
Might be. I have 3 Atom windows open, and one (or even more) of my projects do have a `.jshintrc`.

**Comment by Arcanemagus** [comment]
Please file a new issue if this is still a problem after updating to v2.0.0.
