### ISSUE TITLE
linter-jshint causes Atom to hang for up to 30 seconds on large files

### ISSUE THREAD

**Issue by giedrius-timinskis** [AtomLinter/linter-jshint#162]
I was loading the materialize.js file from the Materialize framework, and the Atom editor was unresponsive for around 30 seconds. I disabled the js-lint plugin, and the file opened immediately.

Let me know if I can provide any additional information.

**Comment by steelbrain** [comment]
Yep, that's because we're running everything in the main thread. I did advise @iam4x about running cpu intensive calculations in a separate thread, but haven't received any reply yet.

**Comment by steelbrain** [comment]
I am unable to repro this on the latest version, everything is run in a separate thread.
