### ISSUE TITLE
errors cover code when i was coding

### ISSUE THREAD

**Issue by albin3** [AtomLinter/linter-jshint#163]
![pic](http://7xkqu3.com1.z0.glb.clouddn.com/a.png)

when i type 'if (', then i can't see my code any more...

**Comment by steelbrain** [comment]
Sorry bud but this is an issue with the way atom overlays work. You can try keeping the part you're editing in the middle of the screen.

**Comment by albin3** [comment]
You're welcome and I tried to edit in the middle of screen by add many empty lines to the end of my code file. The empty lines is gone when I press 'command+s' to save the file, it seems they are deleted by atom as unusable lines... So, I don't know how to keep coding in the middle of the screen...

Can we change window size when errors/warnings appear ?  I found some [atom api](https://atom.io/docs/api/v1.0.7/Atom#section-Managing The Atom Window) hope will help...

many thanks

**Comment by Eschon** [comment]
You could try the `scroll past end` option in Atom. This way you don't have to add empty lines to your file.

**Comment by albin3** [comment]
It works, thank you @Eschon .
