### ISSUE TITLE
Nothing works after installing without any output

### ISSUE THREAD

**Issue by FinalAir** [AtomLinter/linter-jshint#164]
Context:
Mac OS X Yosemite 10.10.4
Atom 1.0.7

Packages installed:
linter
linter-jshint 1.1.5

As said as title above, nothing works in files with the .js extension optionally inside script blocks in HTML, and no output in atom console.

**Comment by ricardograca** [comment]
And what about after restarting Atom?

**Comment by Arcanemagus** [comment]
Have you manually specified the path to jshint in the settings? OS X has issues with the environment not being defined for applications launched from Spotlight (the GUI?).
