### ISSUE TITLE
Setting to not lint .jsx files?

### ISSUE THREAD

**Issue by proehlen** [AtomLinter/linter-jshint#165]
jshint lints my jsx files giving me dozens of messages that aren't relevant.  I'm wrapping every jsx file with `/*jshint ignore:start */` and `/*jshint ignore:end */` but this seems like a tedious work-around.

Is there or should there be a setting to ignore *.jsx files or should that be default behaviour?

**Comment by mclckr** [comment]
it would also be great to have an option not linting *.min.js files.

**Comment by steelbrain** [comment]
@mclckr We are working on introducing a config to ignore linting specified files in the core linter.

**Comment by augbog** [comment]
:+1:  dealing with this issue as well

**Comment by mclckr** [comment]
@steelbrain looking forward to it ![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by steelbrain** [comment]
@mclckr We're out of ideas, help us https://github.com/atom-community/linter/issues/744

**Comment by proehlen** [comment]
I don't know the detail and maybe I'm sure that I'm quite possibly oversimplifying it,  but jshint doesn't attempt to lint python files. How does it know not to lint .py files?  Can't the same mechanism be employed?   Is there ever a scenario where you'd want to lint a jsx file?  To what end?  You're always going to get dozens of spurious messages. 

The current behavior is a bug in my opinion that shouldn't require configuration to get around.

**Comment by steelbrain** [comment]
@proehlen jshint doesn't lint python files because it doesn't provide the python grammar as it's thing to the base linter. `linter-jshint` itself says that I can lint jsx files by specifying the grammar here https://github.com/AtomLinter/linter-jshint/blob/master/lib/main.coffee#L25
The problem is that some people want this feature, others do not. Temporarily you can just edit `~/.atom/packages/linter-jshint/main.coffee` and remove that grammar and restart atom and it'll work for you

**Comment by proehlen** [comment]
OK,  thank you @steelbrain for the explanation and the work around.

**Comment by Arcanemagus** [comment]
So it looks like this issue split off onto multiple tangents (Not linting minified files and.. linting Python with `jshint`??), in any case there is a setting that enables or disables linting on `source.js.jsx` files currently so I am marking this issue as solved.

If anything has not been covered by this feel free to open a new issue.

**Comment by Arcanemagus** [comment]
Can you check v2.0.1? It should be just as broken as v1.3.1 was, but that brokenness is all within `jshint` so there is nothing we can really do about that...
