### ISSUE TITLE
inline ignore doesn't update until you restart atom

### ISSUE THREAD

**Issue by OmgImAlexis** [AtomLinter/linter-jshint#176]
If you add `// jshint ignore:line` to a line it'll keep showing the error until you restart atom. I'm on the latest version of atom-linter and linter-jshint.

**Comment by Arcanemagus** [comment]
So it looks like this is a bug in `jshint`.

When "Lint Inline Java Script" is enabled this bug shows up, when it is disabled that style of ignoring a line works perfectly.

The _really_ interesting thing though is that enabling that option makes an entirely different set of results show up:
![image](https://cloud.githubusercontent.com/assets/427137/13059066/7c0b4a5a-d3dc-11e5-86cc-311b60ef2ff5.png)


If you are still using jshint and haven't switched to a modern linter for some reason you might want to file an issue on their repo about this.
