### ISSUE TITLE
Option not working: "Disable When No Jshintrc File In Path"

### ISSUE THREAD

**Issue by ts-web** [AtomLinter/linter-jshint#181]
After installing the plugin, I have my `Desktop` directory opened, which has no `.jshintrc` file. But opening my file `es6_test.js` still results in linting from JSHint. 

I have a `.jshintrc` file in `C:/`, but it shouldn't be reading that, according to the documentation.

I have restarted Atom about twice; same result.

**Comment by Arcanemagus** [comment]
It looks like [currently](https://github.com/AtomLinter/linter-jshint/blob/v1.2.1/lib/main.coffee#L49) we are using `helpers.find()` which will search up the drive till it finds a file or hits the root. Either the documentation needs to be updated or a different method of searching for that file needs to be used.

**Comment by steelbrain** [comment]
Does our behavior differ from the CLI jshint?

**Comment by Arcanemagus** [comment]
Actually that's a good point, according to [the docs](http://jshint.com/docs/) `jshint` should be searching up to the drive root as well, so this isn't an issue.

Where were you seeing that it shouldn't be doing that @ts-web?

**Comment by ts-web** [comment]
Oh, I see that the jshint docs specify that behavior of looking up the directory tree for the file.
I will close this issue. Thanks everyone.
