### ISSUE TITLE
Feature Suggestion: global defaults

### ISSUE THREAD

**Issue by ts-web** [AtomLinter/linter-jshint#182]
It would be nice to have this feature -- the ability for me to set a global setting for all the JS files I open on my computer to be linted with a set of default rules. And if there is a jshintrc file in the current project directory, that file takes precedence.

I suggest adding a Settings field -- a path to a global .jshintrc file, which is treated as the default set of rules.

Does anyone else second this idea?

**Comment by steelbrain** [comment]
I'm personally :+1: on this, it's already present in linter-eslint btw

**Comment by ts-web** [comment]
I learned that jshint looks in every directory of the path, up to the filesystem root.
So by putting a `.jshintrc` in `C:/`, this can be accomplished.

**Comment by steebchen** [comment]
It still would be better if you could simply specify a directory or the exact file path. I neither want to create a .jshintrc in every project nor I want to have such a config file in my / directory.

**Comment by Arcanemagus** [comment]
@steebchen You are looking for #339, which probably could have been marked as a duplicate of this.

This is _terrible_ practice btw, but it seems quite a few people prefer it...

**Comment by steebchen** [comment]
Ah, thanks. I have around 20 repositories which I use all by myself and I would like to use the same config for all projects. When other people collaborate in some repositories, I have an extra .jshintrc file in there which is used for the specific project then. Why is it "terrible" practice? It seems quite clever for me.

**Comment by Arcanemagus** [comment]
Maybe you are one of the rare ones that remembers, but I've worked with several people that completely forget to configure shared repos in a manner that works for anyone on the code... since it is perfectly configured on their machine due to global configurations like this.
