### ISSUE TITLE
Single missing comma causes 2 errors and 5 warnings

### ISSUE THREAD

**Issue by adambuczynski** [AtomLinter/linter-jshint#186]
This might belong in the jshint repo, let me know if I should post it there.

The issue is that a single missing comma in an object declaration will trigger 7 different errors/warnings in jshint, rather than just detecting that a comma is missing and showing a single relevant error:

![ss](https://www.dropbox.com/s/7cj73zjok01e8ni/Screenshot%202016-01-05%2008.45.39.png?dl=1)

Not sure if it can be fixed as I don't know the underlying code, but if someone could look at this particular case that'd be great.

**Comment by steelbrain** [comment]
Yep, this definately belongs to the jshint repo. Think of `linter-jshint` as a messenger between the original `jshint` and Atom

**Comment by adambuczynski** [comment]
That's what I though. I'll put it up there. Thanks.
