### ISSUE TITLE
Wrong line numbers reported for JavaScript in HTML body

### ISSUE THREAD

**Issue by rmzelle** [AtomLinter/linter-jshint#187]
I'm getting JSHint errors on the wrong lines for inline JavaScript in the HTML body:

![image](https://cloud.githubusercontent.com/assets/77951/12127167/adc6d32c-b3c3-11e5-9769-203327575489.png)

HTML source: https://gist.github.com/rmzelle/e5bc6f1a30113f69db9c

This is with Atom 1.3.2, linter 1.11.3, and linter-jshint 1.2.2 (with "Lint Inline Java Script" checked).

The HTML validates according to https://validator.w3.org/ and it looks like embedding JS in the body is indeed allowed: http://stackoverflow.com/a/1362192/1712389

If I move the JS to `<head/>` I get correct line numbers.

**Comment by Arcanemagus** [comment]
You would need to file this over on [`jshint`](https://github.com/jshint/jshint/issues/new), looks like a bug with their extraction code not properly sending back the correct line number. Can you file a new issue over there (and link back to this one so we can see what happens with it.

We simply report what `jshint` gives us :wink:.

**Comment by rmzelle** [comment]
Done, thanks.

**Comment by Arcanemagus** [comment]
Thanks for reporting it, hopefully they can get it fixed :wink:.
