### ISSUE TITLE
Cannot use custom config .jshintrc

### ISSUE THREAD

**Issue by rootasjey** [AtomLinter/linter-jshint#201]
Hello,

I've recently tried to use my own config to use the Linter Jshint pluging but whatever the file, I get the following error:

>Error: C:\Users\toto\Desktop\toto.jshintrc:5 "passfail" : false, // Stop on first error. ^
> "passfail" : false, // Stop on first error. ^

>SyntaxError: Unexpected token : at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:413:25) at Object.Module._extensions..js (module.js:452:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:475:10) at startup (node.js:129:18) at node.js:981:3

Do you have any idea why I get this error?
Without a custom config file, the plugin works as expected.

(I only have linter-jshint activated.)

**Comment by Arcanemagus** [comment]
Without your `.jshintrc` file it's hard to reproduce this to diagnose it, but it looks like you are trying to use a `passfail` option, which doesn't seem to be in [the list of options](http://jshint.com/docs/options/)...

**Comment by rootasjey** [comment]
Sure, sorry.
Found it! 
It was the comments inside the json object which are not allowed.

```JavaScript
{
    // Settings
    "passfail"      : false,  // Stop on first error.
    "maxerr"        : 100,    // Maximum error before stopping.

    // Predefined globals whom JSHint will ignore.
    "browser"       : true,   // Standard browser globals e.g. `window`, `document`.
    "node"          : false,
    "jquery"        : true,

    "predef"        : [  // Custom globals.
        //"exampleVar",
        //"anotherCoolGlobal",
        //"iLoveDouglas"
    ],
}
```

**Comment by Arcanemagus** [comment]
Ah, yea, pure JSON has no support for comments (One of the many reasons I'm glad `eslint` at least now supports many different config styles is that most of them _properly_ support comments, instead of the "hacked into the JSON" method it used to use...).
