### ISSUE TITLE
Invalid TextEditor Provided

### ISSUE THREAD

**Issue by lakiluki1** [AtomLinter/linter-jshint#207]
Getting the following error when editing a javascript file with linter-jshint and linter installed. 
Running Arch Linux.

> Error: Invalid TextEditor provided
    at _validateEditor (/home/[username]/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:143:11)
    at Object.rangeFromLineNumber (/home/[username]/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:164:3)
    at /home/[username]/.atom/packages/linter-jshint/lib/main.coffee:88:31
    at Array.map (native)
    at /home/[username]/.atom/packages/linter-jshint/lib/main.coffee:77:25

EDIT: Just tried linter-php and getting a similar issue regarding Invalid TextEditor provided

**Comment by Arcanemagus** [comment]
You need to update your Atom, this is a bug in the `atom-linter` helper library that only shows up on Atom <1.4.0.

**Comment by Arcanemagus** [comment]
Specifically https://github.com/AtomLinter/atom-linter/issues/107, which is fixed in https://github.com/AtomLinter/atom-linter/pull/106.
