### ISSUE TITLE
Error on jekyll-powered HTML files

### ISSUE THREAD

**Issue by jonathanwiesel** [AtomLinter/linter-jshint#21]
The linter start to go nuts on the front-matter of html files from jekyll site:

```html
---
layout: main
---
<div class="wrapper">
...
</div>
```

**Comment by hd-deman** [comment]
to disable for HTML, [@syntax](https://github.com/AtomLinter/linter-jshint/blob/master/lib/linter-jshint.coffee#L80) must be configurable.

**Comment by envygeeks** [comment]
Can we please get a fix for this?

**Comment by evanrelf** [comment]
+1

If we could have an option to disable linting for specific syntaxes, that would be great.

**Comment by steelbrain** [comment]
Fixed long ago
