### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Bulan** [AtomLinter/linter-jshint#232]
When I edit a html file with embedded javascript (Polymer), I suddenly started to get a lot of popups with this error:

```
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:457:29)
    at Object.<anonymous> (/Users/bulan/.atom/packages/linter-jshint/lib/main.js:141:57)
    at [object Generator].next (native)
    at step (/Users/bulan/.atom/packages/linter-jshint/lib/main.js:3:273)
```

**Comment by steelbrain** [comment]
This has been worked around for a long long time, try updating  your `linter-jshint`

**Comment by Arcanemagus** [comment]
Actually that might be triggered if the line is undefined, we aren't checking for that it seems.

@Bulan Can you share the file you were editing when you saw this?

**Comment by Bulan** [comment]
@steelbrain I have version 2.0.2 (Which I assume is the latest as there's no update available).

@Arcanemagus I disabled jshint when this started, and the file is now at least 15 iterations later, and I don't really remember which of all the files it was, so I have quite a hard time to provide that file unfortunately.
I do remember that I was editing the properties of a Polymer component when this happened.
Something along the lines like this:
`    properties : {
      activity  : Object,
      dueStatus : {
        type: String,
        computed: '_getDueStatus(activity)'
      }
    },
`

Currently I can't reproduce it with the status of the files, but I'll leave jshint enabled and see if it pops up again.

**Comment by Arcanemagus** [comment]
Without the raw error from `jshint` there isn't really a way to debug this further. If you run into this again please report back and re-open this, for now though I'm closing this.

**Comment by Bulan** [comment]
Ok, I got the error again now.

As soon as I try to edit anything(I think), like just adding a space within the script block, I get the error.

[task-list-template.html.zip](https://github.com/AtomLinter/linter-jshint/files/164838/task-list-template.html.zip)

**Comment by Bulan** [comment]
@Arcanemagus Could you reopen this? I can't seem to do it myself.

**Comment by Arcanemagus** [comment]
Looking into this now.

**Comment by Arcanemagus** [comment]
This is yet another bug in `jshint`:
![image](https://cloud.githubusercontent.com/assets/427137/13711505/c5566690-e773-11e5-8acc-3173d35e782b.png)

It's claiming there is an error on line 100... in a file with 85 lines.

I'll put in a check that will at least show a better error message, but the root issue needs to be fixed there.

**Comment by Arcanemagus** [comment]
Is there any particular reason you aren't using a modern JS linter like `eslint`?

**Comment by Arcanemagus** [comment]
v2.0.3 is released which silently works around this issue and sets the line to the last line of the file.

**Comment by Bulan** [comment]
Reason behind not using a modern linter is simply I didn't know there was options. 😵
(Even this plugin is named jshint)
