### ISSUE TITLE
Linter stops working with this package

### ISSUE THREAD

**Issue by amucinom** [AtomLinter/linter-jshint#239]
Hello!

I have noticed that since version 1.4.0~, the linter stopped working when used in conjunction with this other package: https://github.com/gandm/language-babel, which is a language grammar that transpiles ES6 codes. It used to lint the file, but now it doesn't anymore, although I would assume it should still do it, since the file extension is still *.js

Wondering if this could be looked into

**Comment by Arcanemagus** [comment]
I'm betting that that language package is setting the grammar to something non-standard. What do you get in a file that should be working if you run the `Editor: Log Cursor Scope` command from the Command Palette?

**Comment by amucinom** [comment]
I'm getting source.js.jsx, which should work. Honestly it could be something I'm not taking into account or another package I have installed. I'll do some more digging and post what I find!

**Comment by Arcanemagus** [comment]
That scope will only work if you have the "Lint JSX Files" option enabled btw.

**Comment by amucinom** [comment]
Found the issue! I had to specify the path for jshint instead of letting it use the one it comes with!
