### ISSUE TITLE
Running on *.jsx pages

### ISSUE THREAD

**Issue by avanderhoorn** [AtomLinter/linter-jshint#24]
When I open my *.jsx files (react), atom linter-jshint is being run on the page. At first I thought this was a problem with my `.jshintrc` setup but when I run jshint directly it ignores those files. Hence, I'm guessing its a problem with linter-jshint - maybe its looking for a contains *.js pattern rather than ends with. Any thoughts?

**Comment by iam4x** [comment]
@avanderhoorn @hmalphettes Use `linter-jsxhint`

**Comment by hmalphettes** [comment]
@iam4x , I know; I proudly contributed linter-jsxhint: https://github.com/AtomLinter/linter-jsxhint/commit/44d135615ef8fc92adf023c326c1273218cbd09d

**Comment by iam4x** [comment]
Sorry didn't pay attention :)

**Comment by hmalphettes** [comment]
@iam4x thanks for the kind attention to suggest it.
Not sure why I felt the urge to claim karma credits for it.

**Comment by thewebdreamer** [comment]
@iam4x Well jsxhint has been deprecated since July 2015... https://github.com/STRML/JSXHint/commit/05212f6ccfafe401779b296f97924c30fdd66fb2

**Comment by steelbrain** [comment]
@thewebdreamer Aaha!

**Comment by Arcanemagus** [comment]
Published in v1.3.0.

**Comment by BlaM** [comment]
Are there any requirements to lint React/jsx syntax? It still gives me that little Exclamation-Mark icon:

![image](https://cloud.githubusercontent.com/assets/176011/16224945/9cedbfec-37a4-11e6-885a-e5659e0fa089.png)

Or will that just happen and I need to use `/* jshint ignore:start */`?

**Comment by Arcanemagus** [comment]
@BlaM That must be coming from another package, you can try running Atom in safe mode (`atom --safe`) to check.
