### ISSUE TITLE
Provide explanation link to https://jslinterrors.com

### ISSUE THREAD

**Issue by camlafit** [AtomLinter/linter-jshint#246]
Hi

Would be nice to get a link to explanation issue detected.
Jshint is not enough verbose to understand issue detected in some case. 

Maybe add a link on W0xx to https://jslinterrors.com/w0xx can be usefull.

Thanks a lot

**Comment by camlafit** [comment]
Hum

As some error are not listed on this site, maybe to result search  page as https://jslinterrors.com/?q=w0xx

**Comment by Arcanemagus** [comment]
I may eventually get to this, but as this project has no active maintainer this will get implemented much quicker if you put together a PR for this (which is a good step to becoming a maintainer if you were interested :wink:).

**Comment by camlafit** [comment]
Hi

It's a try to provide a PR about this issue. It's working on mine instance :)

**Comment by Arcanemagus** [comment]
Closed in #247.
