### ISSUE TITLE
Custom js-hint filename

### ISSUE THREAD

**Issue by jeremieca** [AtomLinter/linter-jshint#255]
Hello,

I would like to use a custom config file for linter-jshint (different from default : .jshintrc).
How to change the config path with Atom ?

Thanks !

**Comment by Arcanemagus** [comment]
Fixed in #252, which simply hasn't been released yet. I'll get that out in a few minutes!

**Comment by Arcanemagus** [comment]
v2.1.0 published including an option for this.

**Comment by jeremieca** [comment]
Thanks but where is the option ?
I don't see it in settings of the linter-jshint package.

**Comment by jeremieca** [comment]
It's ok, I just need to add this in ~/.atom/config.cson

`
  "linter-jshint":
    jshintFileName: "path/jshint.json"
`
