### ISSUE TITLE
jshint 'extend' not working

### ISSUE THREAD

**Issue by adarrra** [AtomLinter/linter-jshint#276]
hi!
This breaks in version 2.1.0 only
I have .jshintrc in project folder and also in one nested folder I have .jshintrc with following:
```
{
    "extends": "../.jshintrc.browser"
}
```
So I expect that all files in this nested directory will be validate due to this extended version
But in 2.1.0 linter ignore this extension.

**Comment by Arcanemagus** [comment]
So `linter-jshint` v2.0.4 works but v2.1.0 doesn't?

**Comment by adarrra** [comment]
after several reinstallation for testing versions everything works fine... So I suppose issue could be closed..
Sorry for bothering.

**Comment by Arcanemagus** [comment]
No problem, glad it's working for you!
