### ISSUE TITLE
.jshintrc only read on first lint

### ISSUE THREAD

**Issue by petey** [AtomLinter/linter-jshint#277]
jshint now expects `esversion: 6` instead of `esnext` and esnext is deprecated. I am getting warnings from linter now, even with `esnext` checked against ES6 specific keywords and operators like `const` and `=>`.

**Comment by Arcanemagus** [comment]
Did you mean to file this on [linter-jscs](https://github.com/AtomLinter/linter-jscs)? `jshint` has never had either of those options to my knowledge, while `jscs` does/did and recently released v3.0.0 making the changes you outline above.

It looks like I forgot to publish a release with that update though, I'll push that out now!

Marking this as closed since I'm pretty sure this is the wrong repository.

**Comment by petey** [comment]
No, I really do mean linter-jshint. I don't have linter-jscs installed.

Here's the deprecation notice for esnext: http://jshint.com/docs/options/#esnext
And the esversion configuration: http://jshint.com/docs/options/#esversion
The issue in jshint: https://github.com/jshint/jshint/issues/2124
And the release notes for the version in which it was added: http://jshint.com/blog/2015-09-03/release-2-9-0/

**Comment by petey** [comment]
In case that isn't enough proof, here's a screencap of the warning in atom from jshint:

<img width="661" alt="screen shot 2016-05-05 at 11 02 31 pm" src="https://cloud.githubusercontent.com/assets/78533/15065528/8bb144aa-1315-11e6-9bfe-88864a3cf85a.png">

**Comment by Arcanemagus** [comment]
That's all part of your configuration file, not something that is part of this plugin. Does `jshint` show the same message when run from the CLI?

If _doesn't_ are you able to share your project's files so I can look into what is breaking when it is being run through Atom?

**Comment by petey** [comment]
I have a .jshintrc  in the repo which will silence the warning when running `jshint` on the CLI, but the plugin doesn't read that for some reason.

```
{
  "esversion": 6,
  "node": true
}
```

I had thought there was an `esnext` checkbox provided by this plugin, but that was just something I had added in my local config, and probably didn't do anything, since `esversion` doesn't either.

I can reproduce this by creating a new javascript file with the contents:
```
const foo = "bar";
```

**Comment by petey** [comment]
ugh. ok. So the real issue is that the .jshintrc is only read when atom starts. So if it is not present when atom starts, it won't use those settings if added later.

**Comment by Arcanemagus** [comment]
Checking on that now

**Comment by Arcanemagus** [comment]
Hmmm, I can't reproduce that.

If I open `foo.js` with the file contents as you gave above and lint it (correctly) shows no messages from  `jshint`. If I then set `esversion` to 3 in another tab, save, and then lint `foo.js` again it correctly shows a message about const being available in ES6.

**Comment by petey** [comment]
Yeah, it is more of an issue of `.jshintrc` existing in the first place. If the `.jshintrc` doesn't exist, you can add one, and those settings don't appear to be loaded until the entire window is reloaded.

**Comment by Arcanemagus** [comment]
So you're saying these steps?

1. Create a blank folder
2. Open Atom in this folder
3. Create and save a `foo.js` with these contents:

  ```js
  const foo = "bar";
  ```
4. Run a lint on that file (Does the "Disable jshint when no config" option have to be disabled?
5. Create and save a `.jshintrc` file with these contents:

  ```json
  {
    "esversion": 6,
    "node": true
  }
  ```
6. Run a lint on `foo.js`, note it failing to take the configuration into account

**Comment by Arcanemagus** [comment]
Hmmm, that's not it as the above steps work perfectly for me.

**Comment by petey** [comment]
I can reproduce with exactly the steps you listed and "Disable jshint when no config" is not checked.

**Comment by Arcanemagus** [comment]
Hmmm, I can't :confused:

https://youtu.be/DLEQ9o_KngM

**Comment by petey** [comment]
I can work around.
