### ISSUE TITLE
Errors distributed badly when 2 panes contain same file

### ISSUE THREAD

**Issue by alexnewmannn** [AtomLinter/linter-jshint#282]
I had opened up 2 panes in Atom, and accidentally left the same file open in another pane.
I was getting a list of 10 errors but only 2 or 3 showing in the file, which was driving me mad. Turns out I had the file open in another pane (even though it had the latest changes and was synced) but the other 7-8 errors were on that version of the file.

Let me know if any questions, it's an odd one and got me for a good 20 minutes haha.

**Comment by Arcanemagus** [comment]
@steelbrain Isn't this fixed in `linter-ui-default`?

**Comment by steelbrain** [comment]
It is

**Comment by Arcanemagus** [comment]
Okay, marking this as closed/external then.

**Comment by alexnewmannn** [comment]
spot on, cheers guys
