### ISSUE TITLE
Getting ES6 warnings despite having esversion: 6

### ISSUE THREAD

**Issue by agawley** [AtomLinter/linter-jshint#284]
I have set esversion to 6 in the jshint settings but I still get a bunch of ES6 warnings when linting.

Here is my full config file:

```cson
"*":
  core: {}
  editor:
    showIndentGuide: true
    tabLength: 4
  "exception-reporting":
    userId: "57c2e5dd-4b1a-a069-b7c7-8da3a099feb5"
  "linter-jshint":
    esversion: 6
  welcome:
    showOnStartup: false
```

The errors I am seeing are:

<img width="678" alt="screen shot 2016-05-15 at 7 41 16 am" src="https://cloud.githubusercontent.com/assets/16578/15274804/7af0f996-1a70-11e6-9d0c-e3e2b8f7f083.png">

**Comment by Arcanemagus** [comment]
It looks like you tried to put the configuration in your Atom configuration. You need to create a [`.jshintrc` file](http://jshint.com/docs/) and specify the option in there for it to work.

**Comment by agawley** [comment]
Yup figured it out. Thanks!

**Comment by manngo** [comment]
I was having the same problem and found this.

Why is the option available in the Settings if it doesn’t work?

**Comment by Arcanemagus** [comment]
@manngo There is no such option in [the settings](https://github.com/AtomLinter/linter-jshint/blob/v3.0.3/lib/main.js#L10-L31), so I'm not sure what you are talking about?

**Comment by manngo** [comment]
I understand. I added the option in `~/.atom/config.cson`, and so it must have appeared in the settings.

**Comment by Arcanemagus** [comment]
Ah, yea Atom has the interesting "feature" of attempting to show any settings it finds in the configuration file, regardless of whether the package actually knows about them or not.
