### ISSUE TITLE
Can't configure to lint in <script> blocks

### ISSUE THREAD

**Issue by vorugantia** [AtomLinter/linter-jshint#287]
I tried following the instructions under "Settings" in this link to enable JS lint in script blocks (lintInlineJavaScript: true), but it seems to not be working for me:  https://atom.io/packages/linter-jshint.

Any ideas as to how I can get it to work? Thanks!

**Comment by Arcanemagus** [comment]
How does it "not work" for you? Do you get errors? Does it simply not show anything?

**Comment by vorugantia** [comment]
Sorry for not clarifying. I enabling lint in script blocks as mentioned and the file saved with my changes, but they still had no effect on my script block. No errors showed up.

**Comment by Arcanemagus** [comment]
It will only trigger a lint if your cursor is within the script block, did you have it there or in the HTML section?

**Comment by vorugantia** [comment]
I've tried it with my cursor in the script block and it still doesn't detect an error if I type one in.

**Comment by Arcanemagus** [comment]
Are you able to share the file?

If you place your cursor in there and then run `Editor: Log Cursor Scope` what does it show?

**Comment by vorugantia** [comment]
I'll send my config file in txt format. [config.txt](https://github.com/AtomLinter/linter-jshint/files/267150/config.txt)

When running the command, this pops up:


Scopes at Cursor

- text.html.basic

- source.js.embedded.html

**Comment by Arcanemagus** [comment]
Was the `linter` package properly installed for you? If not, please manually install it. Also I meant the HTML file you are having issues with.

**Comment by vorugantia** [comment]
Well, I installed linter and linter-htmlhint as well as the JS one and I seem to get the error messages for HTML just fine. I also do get error messages from linter-jshint, but only in .js files.

I just tested the linter in a test file: [test.txt](https://github.com/AtomLinter/linter-jshint/files/267164/test.txt)

**Comment by Arcanemagus** [comment]
It seems to be working fine for me:
![image](https://cloud.githubusercontent.com/assets/427137/15331288/72af329c-1c15-11e6-822b-a63cbd55205c.png)

Are your settings any different?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having issues feel free to respond further!
