### ISSUE TITLE
Not able to uninstall

### ISSUE THREAD

**Issue by RYG81** [AtomLinter/linter-jshint#289]
Hi some how the plugin stopped working for me. Now when I try to uninstall it , it fails every time.
What to do if I want to re-intsall it.

**Comment by Arcanemagus** [comment]
I think I saw somewhere Atom has a bug where it reports failure, but really uninstalls a package. YOu should always be able to close all instances of Atom and then run `apm uninstall linter-jshint` to uninstall it, and then `apm install linter-jshint` to install it again.
