### ISSUE TITLE
Problem with Chocolatey

### ISSUE THREAD

**Issue by FelschR** [AtomLinter/linter-jshint#29]
I installed Atom on Windows via Chocolatey.
The following file could not be found.

file:///C:/ProgramData/chocolatey/lib/Atom.0.113.0/tools/Atom/resources/app/static/c:/Users/<USER-NAME>/.atom/packages/linter-jsonlint/lib/init.coffee

**Comment by steelbrain** [comment]
Atom doesn't use chocolatey anymore.
