### ISSUE TITLE
Jshint not disabling when no .jshintrc found

### ISSUE THREAD

**Issue by andrewmartin** [AtomLinter/linter-jshint#291]
For some reason, jshint is always linting no matter what.

I have this setting checked:
![](http://cloud.believelabs.com/2C200r2L2n21/Image%202016-06-16%20at%2016.53.40.png)

I've tried restarting Atom a few times, to no avail. Any other suggestions?

**Comment by Arcanemagus** [comment]
Do you have a `.jshintrc` file in any parent directory of your projects?

**Comment by andrewmartin** [comment]
@Arcanemagus Not in this particular project, no.

**Comment by andrewmartin** [comment]
I've noticed that now, when I have all three boxes checked, `jshint` always runs, no matter what. If I uncheck "Lint JSX Files," it seems to work as expected.

![](http://cloud.believelabs.com/0H3q120G3h3A/Image%202016-06-30%20at%2017.17.53.png)

**Comment by macgyver** [comment]
Same problem here, definitely no `.jshintrc` in any preceding folders.. normally I'd just +1 the initial comment but seems like this thread could use a bump..

**Comment by Arcanemagus** [comment]
Supposedly fixed in #335, will need testing once that gets released.
