### ISSUE TITLE
Enable linting for "Babel ES6 JavaScript" grammar

### ISSUE THREAD

**Issue by samselikoff** [AtomLinter/linter-jshint#294]
Hi! Thanks for this great package.

I came across [this issue](https://github.com/AtomLinter/linter-jshint/issues/239) but the OP's solution didn't help. I'm trying to get jshint running on my JavaScript files, which use the grammar "Babel ES6 JavaScript". Is this possible?

I believe my paths are configured correctly, because if I manually change the syntax of the current file, jshint runs and warns about unused variables.

Any help much appreciated - thanks!

**Comment by Arcanemagus** [comment]
What do you get when you run `Editor: Log Cursor Scope` from the command palette?

**Comment by samselikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/2922250/16286886/4e587534-38ad-11e6-9569-ca893ebb5d5a.png)

**Comment by samselikoff** [comment]
Ah - it's exactly what you said in the other issue. Sorry, I tried to log the cursor scope before, not sure why it wasn't working.

I wonder why it's .jsx? I guess that's just what the grammer uses.

Thanks!

**Comment by Arcanemagus** [comment]
Looks like whatever language package you are using is from when JSX was (badly) used somewhat interchangeably with ES6. You can get `linter-jshint` to run on the file using the "Lint JSX Files" option, as I'm guessing you already figured out since you closed this 😉.
