### ISSUE TITLE
Website http://jslinterrors.com/ down

### ISSUE THREAD

**Issue by rugk** [AtomLinter/linter-jshint#296]
Currently the plugin links to http://jslinterrors.com/ when clicking on errors.

As an example:
http://jslinterrors.com/W095

However this site is down (as said by Cloudflare). Also why not link to the official site http://jshint.com/?

**Comment by rugk** [comment]
Okay, http://jslinterrors.com/ is there again.

**Comment by Arcanemagus** [comment]
jshint.com doesn't actually have any documentation of the rules as far as I can see. If you find an official source of documentation feel free to submit a PR switching to it.

Also it seems that not even jslinterrors.com has an explination for `W095`.

**Comment by rugk** [comment]
Again: "The page you are looking for cannot be found."
http://jslinterrors.com/  seems to be  a bit unreliable - although they use Cloudflare.

**Comment by rugk** [comment]
Ah wait...

**Comment by rugk** [comment]
This error is actually a strange 404 error message delivered by Cloudflare. Oh, so confusing... :confounded:

**Comment by Arcanemagus** [comment]
Fixed in #337.
