### ISSUE TITLE
I think there is nothing wrong with these two statements

### ISSUE THREAD

**Issue by beizhedenglong** [AtomLinter/linter-jshint#309]
![image](https://cloud.githubusercontent.com/assets/12963675/17067326/e00d7618-507d-11e6-8a77-4a037cac7a48.png)
![image](https://cloud.githubusercontent.com/assets/12963675/17067368/02a272a0-507e-11e6-8cad-eecac7dccfc4.png)

**Comment by Arcanemagus** [comment]
You should file that over on the [JSHint](https://github.com/jshint/jshint/issues) repository then, this project is merly integration of it into Atom.
