### ISSUE TITLE
Respect JSHint Configrautions

### ISSUE THREAD

**Issue by lijunle** [AtomLinter/linter-jshint#31]
According to [JSHint docs][1], there are three ways to configure JSHint:

[1]: http://jshint.com/docs/

0. Specify with `--config` option
0. `.jshintrc` file under project hierarchy
0. `package.json` file under project root

And, of course, JS file inline configuration. Something like this:

```
/* jshint undef: true, unused: true */
/* global MY_GLOBAL */
```

Regarding `.jshintrc` configuration file, notice this sentence:

>  In case of .jshintrc, JSHint will start looking for this file in the same directory as the file that's being linted. If not found, it will move one level up the directory tree all the way up to the filesystem root.

But, because AtomLinter save the atom content buffer to a temporary file, it will **NOT** respect the above rule. Besides, AtomLinter does not expose the `--config` option to the end-user.

Currently, the only way to configure JSHint is to add inline directives. Once the project contains many files, this is a nightmare.

Please consider to add support to respect the JSHint rules.

**Comment by Trudko** [comment]
I would like to see setting for config option

**Comment by steelbrain** [comment]
.jshintrc and package.json both are respected now.
