### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by wabudd1** [AtomLinter/linter-jshint#316]
Error numbers have clickable links that go to a dead domain.  Example:
[W098](http://jslinterrors.com/W098) - 'data' is defined but never used.

I'm not sure if this is fixable, beyond simply ripping the links out entirely.

**Comment by Arcanemagus** [comment]
Oh wow, that was working as of a month ago (#297).

It might be possible to link to sections of [this page](http://jshint.com/docs/options/), assuming those names are accessible somewhere. It doesn't look like JSHint documents anything by their error codes though.

If you want to put up a PR either implementing that or removing the dead links that would be great!

**Comment by wabudd1** [comment]
I removed it.  I agree, I don't see anywhere where they document their error codes.  Seems a little silly.

**Comment by RyanJWilliams** [comment]
I've reached out to the owners of the website to see if they're planning to restore it to life.

**Comment by RyanJWilliams** [comment]
Never heard back.
