### ISSUE TITLE
JSHint breaks Emmet in HTML files

### ISSUE THREAD

**Issue by fburleigh** [AtomLinter/linter-jshint#32]
I admit I don't understand why JSHint looks at lines of HTML, but it does.  And with JSHint enabled, some Emmet expansions don't run, e.g. "html:5" followed by tap on tab in a fresh HTML file does nothing (obvious).

Facts:
- OS X
- Atom .17
- Current linter package
- Current linter-jshint package
- default path to jshint
- no other config of jshint

Thank you.

**Comment by steelbrain** [comment]
Fixed long ago
