### ISSUE TITLE
lint errors not going away when fixed with multiple panes

### ISSUE THREAD

**Issue by peonmodel** [AtomLinter/linter-jshint#322]
not too sure if the bug to be post here or in the base linter

jshint panel will open up when a jshint issue is detected in a file, fixing the issue should close the panel

however, when the same file is opened with another tab in atom, (split-right or similar), the jshint panel will not be updated when the jshint issue is fixed

problem only resolve itself when the tabs with the file is closed, down to 1 open tab

**Comment by Arcanemagus** [comment]
This should be filed on the base `linter` package, this is only a provider of messages for it. It's up to `linter` when to refresh (make another call to `linter-jshint`) those messages, and when/how to display them.

That being said, if this is the issue I'm thinking of the fix requires an entire re-write... which has already been done in `linter-ui-default`. If you want to test that out instructions are available [over there](https://github.com/steelbrain/linter-ui-default).
