### ISSUE TITLE
Strict Mode

### ISSUE THREAD

**Issue by TJProgrammer** [AtomLinter/linter-jshint#325]
Hello!
Why JsLint gives a warning when a js file have `"use strict";`?

**Comment by Arcanemagus** [comment]
If I had to guess, either you are using that at the file scope in ES5 code (which can propagate to other files, which is a _bad thing_), or you used it in an ES2015 module which is no matter what in `strict` mode.

In either case, that's a question for JSHint and has nothing to do with this package, which is just a translation for `jshint` bringing its messages into Atom.

**Comment by TJProgrammer** [comment]
Thanks for the explanation.
