### ISSUE TITLE
"Lint JSX Files" doesn't seem to work

### ISSUE THREAD

**Issue by macgyver** [AtomLinter/linter-jshint#331]
The "Lint JSX Files" option doesn't seem to work at all - any jsx at all results in a `E015 - Unclosed regular expression`

Also, it's not clear how it's meant to work - is it just based on file extension?

**Comment by Arcanemagus** [comment]
That option simply toggles running on files identified by the `source.js.jsx` scope, the most common method of identifying as that scope being the file extension (you can always change the language in the lower right corner though).

It used to change a flag passed to JSHint, but at some point they brought support for that into the main linter process by default, so it doesn't change the behavior of the linter at all.

Do you see the same results when running JSHint from the CLI?

**Comment by macgyver** [comment]
No, good point - although I don't see any reference on jshint.com of supporting JSX.. there is a link at the bottom of the [Install page](http://jshint.com/install/) (under *Other cool stuff*) to  https://github.com/CondeNast/JSXHint which makes me think that jshint doesn't actually claim to work for JSX?

**Comment by Arcanemagus** [comment]
It's quite possible. I know it is _very_ buggy with it. You should probably look into using ESLint with the JSX  options enabled, see https://www.npmjs.com/package/eslint-plugin-react for an example of how to set that up.

**Comment by macgyver** [comment]
Thanks :) I've actually already switched to that on projects using JSX, but even after removing the `.jshintrc` file from those projects I'm still seeing the errors (due to #291) so I figured I'd report it.. 

Don't you think you should remove this option from the atom package settings since it definitely doesn't work and probably never will?

**Comment by Arcanemagus** [comment]
Generally I'd leave that up to the package maintainer... but it seems this package has no active maintainer so I'd go for that.
