### ISSUE TITLE
Default .jshintrc

### ISSUE THREAD

**Issue by poisonborz** [AtomLinter/linter-jshint#339]
It would be great to be able to define default .jshintrc options (when none is found). I open standalone/random js files often, and seeing them sprayed with eg. ES6 errors is not pretty.

**Comment by tap52384** [comment]
I agree; I was surprised to find that there are no global defaults currently, or are there?

**Comment by Arcanemagus** [comment]
Well, if you place a `.jshintrc` file in a directory that is a parent to all the projects you want this in, it will use that. So this is somewhat already implemented. There is no way to specify an arbitrary file as the default though.

**Comment by tap52384** [comment]
Does this mean if I have my code in ~/cloudapps/code and I place a file in ~/, it should work?

**Comment by Arcanemagus** [comment]
Correct, that should be working as all parent directories are searched until it hits the file system root, or it finds the requested file.

**Comment by poisonborz** [comment]
It would be really great to to be able to define an arbitrary file... people often open random/non-project files.

**Comment by Arcanemagus** [comment]
That's why this issue is still open @poisonborz 😉. If you want to put up a PR implementing this I'd be happy to review it, this package currently has no active maintainer though so for right now I can only give it sporadic attention unfortunately.

**Comment by Arcanemagus** [comment]
FYI, JSHint supports setting a default `.jshintrc` configuration file in your home directory and using that when no other configuration is found. As of #389 the behavior here will match that for following the "Disable when no configuration file is found" setting.
