### ISSUE TITLE
Link to errors are broken

### ISSUE THREAD

**Issue by surdu** [AtomLinter/linter-jshint#341]
In the error panel, the Wxxx errors link to a domain that appears to have been taken by domain scalpers: http://jslinterrors.com/

**Comment by Arcanemagus** [comment]
Closing as a duplicate of #316, fixed in #337... and apparently not released yet, which I'll do right now 😛.

**Comment by surdu** [comment]
Sorry, searched only opene tickets 😞

**Comment by Arcanemagus** [comment]
No worries, it should have been released a while ago, sorry!
