### ISSUE TITLE
language-babel causes linter-jshint to silently fail

### ISSUE THREAD

**Issue by tap52384** [AtomLinter/linter-jshint#351]
I'm not sure how to provide any debugging information for this issue, but it is definitely repoducible. When the language-babel package is installed, the linter-jshint seems to not understand that the Javascript files are still javascript, and it doesn't lint anything at all. Upon disabling the language-babel package and restarting Atom, the linter works as it is supposed to.

**Comment by Arcanemagus** [comment]
Duplicate of #348.

For some bizarre reason `language-babel` marks _all_ JavasScript files as JSX files.
