### ISSUE TITLE
Error: /Users/*****/.atom/packages/linter-jshint/lib/main.js:5 import Path from 'path' ^^^^^^

### ISSUE THREAD

**Issue by ktravelet** [AtomLinter/linter-jshint#356]
Hi I'm trying to use this atom package and getting the following error

```
Error: /Users/*****/.atom/packages/linter-jshint/lib/main.js:5 import Path from 'path' ^^^^^^

SyntaxError: Unexpected token import at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:387:25) at Object.Module._extensions..js (module.js:422:10) at Module.load (module.js:357:32) at Function.Module._load (module.js:314:12) at Function.Module.runMain (module.js:447:10) at startup (node.js:154:18) at node.js:416:3
```

I installed via Atom -> preferences -> install

OS: MacOS 10.12
Atom: 1.11.0
Linter: 1.11.18
linter-jshint: 3.0.1

I also tried removing the node-modules folder in linter-jshint

```
/Users/*****/.atom/packages/linter-jshint ∫ rm -rf node_modules/atom-linter
/Users/*****/.atom/packages/linter-jshint ∫ npm install atom-linter@latest
```

And lastly tried 'apm install'

`/Users/****/.atom/packages/linter-jshint ∫ apm install
`

**Comment by Arcanemagus** [comment]
Hmm, a few things here:

- Your Atom is out of date, can you update to v1.11.2?
- Can you try closing _all_ Atom instances, completely removing the `/Users/*****/.atom/packages/linter-jshint` folder, then running `apm install linter-jshint`?

**Comment by klahaeck** [comment]
similar error

`Error: /Users/*******/.nodenv/shims/jshint:3
[ -n "$NODENV_DEBUG" ] && set -x
     ^^^^^^^^^^^^^^^
SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:154:18)
    at node.js:416:3
    at ChildProcess.<anonymous> (/Users/*****/.atom/packages/linter-jshint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)`

**Comment by ktravelet** [comment]
So I found a workaround.  Leaving the "Executable Path" empty seems to do the trick.

**Comment by Arcanemagus** [comment]
@ktravelet That's rather interesting, if you leave it "empty" it will use the default, which is the bundled `jshint`. What did you have it set to before? Is that version of `jshint` v2.9.3?

**Comment by ktravelet** [comment]
ah man I'm sorry for wasting your time, I see what I did.

Old value was:

> .atom/packages/linter-jshint/lib/main.js

When its supposed to be:

> .atom/packages/linter-jshint/node_modules/jshint/bin/jshint

**Comment by Arcanemagus** [comment]
Yea, the requirement to run the jshint _node_ script is somewhat confusing.

On that note, @klahaeck it looks like you are trying to run some sort of wrapper script, instead of the raw `jshint` script.

I'm marking this as closed since it's simply a configuration issue 😉.
