### ISSUE TITLE
linter hanging with 3.0.0

### ISSUE THREAD

**Issue by dkebler** [AtomLinter/linter-jshint#358]
not sure when I upgraded to 3.0 but linter hangs (doesn't remove warnings and errors after they have been remedied).   If I restart atom they are gone.  Works for a bit then hangs.  Doesn't completely hang displays new lints just doesn't remove the fixed ones.

I just upgraded to 3.0.1 so see if that cures it.

Where are your logs kept.  Next time it happens I'll post the log output here.

**Comment by Arcanemagus** [comment]
Whenever a lint is triggered the entire set of messages from this provider are updated with new messages, if that isn't happening then this is a bug in Linter.

Are you seeing this with any other providers?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having problems feel free to continue the discussion!
