### ISSUE TITLE
Escape JSHint Messages in Editor

### ISSUE THREAD

**Issue by plemarquand** [AtomLinter/linter-jshint#36]
If HTML is present in the error message displayed on the bottom bar, it is parsed and rendered. The strings from the user's editor should be escaped.

For example, paste the following into a Javascript file:

    ("test".test('')"<img src='http://i.imgur.com/DKxfHXy.gif'></img>");

![Unescaped HTML](http://i.imgur.com/8sze22h.png "Unescaped HTML")

**Comment by avdg** [comment]
Great bug report, but I'm unable to reproduce this now.

**Comment by steelbrain** [comment]
Done with the latest version
