### ISSUE TITLE
Linter slow at recognising errors.

### ISSUE THREAD

**Issue by tiferrei** [AtomLinter/linter-jshint#360]
Hello there,

please forgive me if this is a very "noob" question, I am incredibly new to the JavaScript world, my apologies if I'm doing something wrong.

When doing some code I realised that the Linter warnings seem to take at least 7 seconds to show up, and the same to disappear after I fix the error.

I thought "well, maybe I'm just runing low on memory so everything is a bit slower" but then I checked the activity monitor and everything's fine, 4GB available, no SWAP used.

What am I doing wrong?

Thank you,
tiferrei

**Comment by Arcanemagus** [comment]
If you run `jshint` on the same file on the CLI, how long does it take? (`time jshint foo.js` on Linux / macOS, `Measure-Command { jshint foo.js }` from PowerShell on Windows)

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. As this is only doing minimal work before launching `jshint`, there isn't anything that we can really do here in the first place.
