### ISSUE TITLE
Error while undo the codes.

### ISSUE THREAD

**Issue by boosters** [AtomLinter/linter-jshint#364]
While I am undone multiple time at once, I am getting this nice big error

Check the screenshot

http://image.prntscr.com/image/2d0c78ec799846f08866cff37332cfc7.png

**Comment by Arcanemagus** [comment]
That looks to be a bug inside JSHint itself. Do you have a file that reproduces it consistently?

**Comment by boosters** [comment]
Yeah I am attaching the file

[currentTime.js.zip](https://github.com/AtomLinter/linter-jshint/files/743820/currentTime.js.zip)

**Comment by Arcanemagus** [comment]
Can you upload the configuration file as well? I'm unable to reproduce with the default settings.

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response. If you are still having this problem please provide a _full_ reproduction case as requested above.
