### ISSUE TITLE
JSHint broken after installing dependency

### ISSUE THREAD

**Issue by pbrocker** [AtomLinter/linter-jshint#376]
Error running JSHint Error: /Users/USERNAME/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4(…)(anonymous function) @ /Users/USERNAME/.atom/packages/linter/lib/linter-registry.js:177

**Comment by Arcanemagus** [comment]
Can you double check your `package.json`? Most commonly this is due to a trailing `,` accidentally added there.

**Comment by pbrocker** [comment]
Couldn't find a trailing ',' in my package.json. So I just deleted the package.json and reinstalled. All seems to be working now.
