### ISSUE TITLE
[Linter] Error running JSHint

### ISSUE THREAD

**Issue by EthanBannister** [AtomLinter/linter-jshint#377]
I have an error that I am unable to resolve.  I have attempted to look for a solution elsewhere and have found issues that appear to be similar, but GitHub forums appear to be either providing no solution and I find myself running in a 'Forum loop'.

I have attempted to reinstall EVERYTHING from scratch (Atom and all of my packages) and it keeps returning to haunt me.

![image](https://cloud.githubusercontent.com/assets/9910708/24885099/a4d21bec-1e1a-11e7-9384-fdd1e99d445a.png)

When I open the console, it states 'TypeError: Converting circular structure to JSON':

![image](https://cloud.githubusercontent.com/assets/9910708/24885365/0e96a538-1e1c-11e7-8a3f-095a8260017c.png)

I have also exported a list of all the packages that I am using for this installation of Atom to a text file using apm, performed a fresh install of Atom on another computer, then used apm to install all the packages noted in that installation file.  This install was successful and jslint had no issues that Atom complained about.

Just in case you need to know, here is my list of installed packages:

atom-autocomplete-php@0.22.2
atom-beautify@0.29.18
atom-bracket-highlight@0.3.2
atom-wrap-in-tag@0.6.0
auto-detect-indentation@1.3.0
autoclose-html@0.23.0
busy-signal@1.3.0
file-icons@2.1.2
highlight-column@0.5.2
highlight-line@0.12.0
highlight-selected@0.13.1
intentions@1.1.2
linter@2.1.2
linter-csslint@1.3.4
linter-htmlhint@1.3.3
linter-jshint@3.0.3
linter-jsonlint@1.3.0
linter-php@1.3.2
linter-ui-default@1.2.2
minimap@4.27.1
minimap-highlight-selected@4.6.1
open-recent@5.0.0
permanent-delete@0.1.5
php-cs-fixer@4.1.0
pigments@0.39.1
python-autopep8@0.1.3
smart-tags@0.1.5
swackets@0.26.0
todo-show@1.11.0

Is there something that I may be missing?

**Comment by EthanBannister** [comment]
I installed the deprecated jshint package (https://atom.io/packages/jshint), then installed linter-jshint, then uninstalled the deprecated jshint package.  After that (and a restart of Atom) all appears to be working now.

Not sure what happened there on my end.  Does this package require the jshint package or some "libraries" from it first?  If so, then perhaps adding that to the docs may be needed in case someone else runs into this issue.

If you need any more info from me to try and figure this out, just let me know.

Thanks!

**Comment by Arcanemagus** [comment]
Looks like that's just an internal bug in `jshint` itself (or specifically the `json` linter it embeds). If you have a file (likely your `package.json`) that reproduces this we can track it down and file it on the `jshint` repo.

**Comment by EthanBannister** [comment]
Looks like I may have spoke too soon.  It's back again.

I have attached a copy of the linter-jshint package.json file.  The original jshint package is completely uninstalled, so I am not sure if that is the culprit.  If I am wrong, please let me know.

I will continue to troubleshoot on my end though.

[package.txt](https://github.com/AtomLinter/linter-jshint/files/914207/package.txt)

**Comment by EthanBannister** [comment]
Okay, not I am all sorts of confused.

I hop on one JS file, the linter-jshint works with no issues.

I hop on another JS file, I get the error.

I will continue to troubleshoot.  There are allot of single-line comments in the JS file that linter-jshint is throwing the error on, so I will start with removing those to see if it is hanging up on something.

**Comment by thrgamon** [comment]
Hey @EthanBannister, did you manage to resolve this?

Tom

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response. It looked like this might be the ever common "parsing your `package.json` blew up" error, but on a closer look it seems this is a bug in JSHint trying to generate the report and hitting a circular reference in its internal data structures.

In either case, this is a bug inside JSHint itself, and should be reported there if you can find a (set of) file that reproduces this.

**Comment by EthanBannister** [comment]
I did not resolve this, no.  However, I am currently writing a JS file using nothing but jQuery (the file where I had been getting the error was written in pure JS) and I am not getting any complaints thus far.

As for the old file, removing the comments did nothing (as I would have expected).

If I have any other issues, I will try to bring them up directly to the JSHint guys to see if they can resolve it.

Thank you in any case.

**Comment by Arcanemagus** [comment]
I'd recommend looking into ESLint, it's a _far_ better written linter for JS.

**Comment by thrgamon** [comment]
Gotcha, I will chase up the issue with JSHint and also checkout ESLint. Cheers!
