### ISSUE TITLE
errors when linting markdown file with YAML header

### ISSUE THREAD

**Issue by borisovg** [AtomLinter/linter-jshint#380]
<img width="412" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3171327/25566433/84461cdc-2dd0-11e7-98fe-b5c6015591f1.png">

FWIW, I am using the `language-markdown` package.

**Comment by Arcanemagus** [comment]
Are you sure you are on the latest version of `language-markdown`? That bug has been fixed there for _ages_.

When you have the cursor in the Javascript section of that file, what do you see when you run `Editor: Log Cursor Scope`?

**Comment by borisovg** [comment]
Funny you should say that: today there was an update for `language-markdown` which brought in some change related to embedded code (burodepeper/language-markdown#173) which made the issue go away.

Except now there is no linting within the script block (although I'm not 100% certain that it ever was).

Anyway, issue is gone now. :)

**Comment by Arcanemagus** [comment]
There _shouldn't_ be, since JSHint doesn't know how to extract the JS there 😉.
