### ISSUE TITLE
ES6 warnings

### ISSUE THREAD

**Issue by johncouldbe** [AtomLinter/linter-jshint#383]
The W119 - template literal syntax warnings that pop up in big blocks blocking my code is driving me mad. It would be great to have an easy switch to disable ES6 warnings.

**Comment by Arcanemagus** [comment]
You'll need to configure JSHint here, this is just a wrapper around running that.

In this case you need to add `esversion: 6` to your `.jshintrc` file, like this:
```json
{
  "esversion": 6
}
```
