### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ilanbiala** [AtomLinter/linter-jshint#39]
It would be great to have a changelog.md which tells users what updates contain API changes, bug fixes, performance changes, etc.

**Comment by ilanbiala** [comment]
@dmnd status? Is this going to happen, or should I just close?

**Comment by hd-deman** [comment]
we decided to use [releases](https://github.com/AtomLinter/linter-jshint/releases) for changelog

**Comment by ilanbiala** [comment]
No changelog there..no info or any text at all..
