### ISSUE TITLE
Disable when no .jshintrc option broken

### ISSUE THREAD

**Issue by ynnoj** [AtomLinter/linter-jshint#391]
As of `3.1.0`, the `Disable When No Jshint File In Path` option is broken. With the option checked and no `.jshintrc` file in the project the linter is still returning results.

**Comment by Arcanemagus** [comment]
The behaviour should be matching `jshint` itself, are you sure you don't have a `.jshintrc` file in any _parent_ folder of the code in question?

**Comment by Arcanemagus** [comment]
You can place a breakpoint [here](https://github.com/AtomLinter/linter-jshint/blob/v3.1.0/lib/main.js#L131) in Atom's Developer Tools and check the value of `configFile` to see what the search returned.

**Comment by ynnoj** [comment]
`configFile` is equal to `null` at that breakpoint. The only `.jshintrc` files in my projects are those from dependencies in `node_modules`.

**Comment by Arcanemagus** [comment]
Hmmm, do you have one in your home directory? Proper support for that fallback was added.

**Comment by ynnoj** [comment]
Nothing global, only at a project level. On projects where I'm using JSHint (with `.jshintrc`) the linter is working as expected.

I'm using ESLint (with `eslintrc.js`) on the problematic projects.

**Comment by Arcanemagus** [comment]
Ah ha! I think I see what the bug might be. I forgot to `await` on the return of the "home config" check.

**Comment by Arcanemagus** [comment]
This should hopefully be fixed in v3.1.1.

**Comment by ynnoj** [comment]
@Arcanemagus Confirmed. Thanks for the swift response 🎉
