### ISSUE TITLE
still getting errors in ES6

### ISSUE THREAD

**Issue by broros** [AtomLinter/linter-jshint#395]
![screen shot 2017-05-08 at 6 46 39 pm](https://cloud.githubusercontent.com/assets/598228/25832418/525b409e-341f-11e7-868f-23c4a9add097.png)

.jshintrc
```
{
  "esversion": 6
}
```

**Comment by Arcanemagus** [comment]
Your screenshot is showing JSX, not ES6. You'll need to use a modern linter such as ESLint and configure it properly to support JSX in order to lint code like that. Look for tutorials on linting React code.

JSHint has no support for linting that code.
