### ISSUE TITLE
"Disable when no jshintrc..." option still broken

### ISSUE THREAD

**Issue by gabmontes** [AtomLinter/linter-jshint#396]
I have a `.jshintrc` file in my project's root and linter works OK when `Disabled when no jsnintrc..." option is unchecked. But when checked, the linter does not work at all.

Following the conversation in #391 I see the code is returning here: https://github.com/AtomLinter/linter-jshint/blob/v3.1.0/lib/main.js#L128.

I'm already running on v3.1.1.

PS: Is `await helpers.hasHomeConfig()` in L127 when you already have `configFile` in the lines just above?

**Comment by Arcanemagus** [comment]
Looking into this now.

**Comment by Arcanemagus** [comment]
Fixed in v3.1.2.
