### ISSUE TITLE
'Disable when no .jshintrc file found in path' is broken

### ISSUE THREAD

**Issue by thejameskyle** [AtomLinter/linter-jshint#40]
Since some projects use JSHint and other ESLint, I end up needing to turn them on and off all the time so they won't bother me.

Having an option that will only run linter-jshint when the `.jshintrc` file is found would fix this.

**Comment by sgtpepper43** [comment]
+1!
The jscs linter has this option, this should have it too.

**Comment by keirlawson** [comment]
+1

**Comment by whitlockjc** [comment]
+1

**Comment by mafredri** [comment]
This seems to have been implemented in the latest version, however, the linter stays disabled even with a `.jshintrc` file in my project root.

**Comment by fyockm** [comment]
Having the same problem as @mafredri. with the 'Disable when no .jshintrc file found in path' option selected, linter-jshint stays disabled even when a `.jshintrc` file is in my project root. Is there something in particular that must be done for this to work?

**Comment by n370** [comment]
Same as @mafredri and @fyockm here.

**Comment by AsaAyers** [comment]
Listing is about improving and maintaining code quality. Why would you ever
want the linter to not run?

**Comment by thejameskyle** [comment]
@AsaAyers When different linters are being used on different projects. I only want to hear from the relevant linter, especially when there are conflicts in configuration.

**Comment by fyockm** [comment]
Exactly. I'm using eslint on one project and jshint on another. the "Disable when no .eslintrc file found in path" option works correctly with [linter-eslint](https://github.com/AtomLinter/linter-eslint), so that might be a good reference?

**Comment by AsaAyers** [comment]
oh, so IMO it makes more sense to disable linting if `.eslintrc` is found than to disable when `.jshintrc` is missing.

Maybe in the core linter we need a way to resolve conflicts. `linter-eslint` and `linter-jshint` both claim to lint `source.js` files but I can see where you'd only want to use one.

**Comment by mafredri** [comment]
> oh, so IMO it makes more sense to disable linting if .eslintrc is found than to disable when .jshintrc is missing.

Say there were 10 different javascript linters, you honestly believe that `linter-jshint` should know about all those linters and disable itself it any of their `rc`s are present?

**Comment by thejameskyle** [comment]
Rather than continuing to debate it, why not just make this an option? I can look into making a PR

**Comment by AsaAyers** [comment]
I suppose it doesn't scale very far.

If you aren't aware, there is a rewrite of the core linter in progress. I opened https://github.com/AtomLinter/linter-plus/issues/31 so we can try addressing this in the core.

I don't think it makes sense to ignore linting just because you haven't configured the project you're working on. But it definitely makes sense to avoid running multiple conflicting linters on the same code.

**Comment by AsaAyers** [comment]
No one is preventing you from opening a PR. I'm simply suggesting that it might not be the most complete solution

**Comment by mafredri** [comment]
@AsaAyers this option is already in `linter-jshint` though, it just doesn't work. Since it's an option it's optional to use it.

**Comment by AsaAyers** [comment]
I have never used this project as I don't use jshint. I've been working on the core linter and just happened to get the email notification. Nothing here indicates that this is an existing feature, it looks like a feature request that hasn't been implemented.

**Comment by mafredri** [comment]
![](https://www.dropbox.com/s/5nbg1cgg94sb04h/Screenshot%202015-06-04%2022.04.21.png?dl=1)

**Comment by AsaAyers** [comment]
ok, I have renamed and marked it as a bug. hopefully this draws the attention of whoever normally maintains this. Or maybe one of you can submit a PR to fix it. (I don't write code for projects I don't use)

**Comment by mafredri** [comment]
Thanks @AsaAyers!
