### ISSUE TITLE
Start linting js when Javascript language selected

### ISSUE THREAD

**Issue by danieldbird** [AtomLinter/linter-jshint#400]
Just wondering if this is possible. Start linting js when Javascript language selected in the bottom right corner, instead of having to save the file as .js
![image](https://cloud.githubusercontent.com/assets/2720368/25977479/fb32d536-370f-11e7-8de9-1c9c2e04c907.png)
Apologies if this is not possible, I am just starting to wrap my head around how atom works. Thanks for the great package.

**Comment by Arcanemagus** [comment]
That's how this already works, unless you have installed something like `language-babel` which _shows_ JavaScript there, but really marks the file as JSX (which isn't supported by JSHint).

**Comment by danieldbird** [comment]
I just installed atom, and my only installed packages are: linter, linter-ui-default, linter-jshint, intentions, busy-signal.
Unless I am misunderstanding you, it only lints on saving the file as .js
![image](https://cloud.githubusercontent.com/assets/2720368/25978606/63bb1378-3717-11e7-9864-694703e0ac57.png)
![image](https://cloud.githubusercontent.com/assets/2720368/25978618/70873348-3717-11e7-9897-cebe416ffca0.png)

**Comment by Arcanemagus** [comment]
Ah ha! You mean on a buffer that has _never_ been saved. Unfortunately this isn't really possible as many of the configuration steps require a file path to determine how things are supposed to work. If you were curious there is some discussion of what to do in this case over in https://github.com/steelbrain/linter/issues/1235, but even if such support were added in `linter` itself, it wouldn't work here.

Once a file has been saved initially, any unsaved changes will be linted.

**Comment by danieldbird** [comment]
Understood, thanks for the information.
