### ISSUE TITLE
linter-jshint can not work

### ISSUE THREAD

**Issue by chen0213sun** [AtomLinter/linter-jshint#406]
![default](https://cloud.githubusercontent.com/assets/23097255/26356240/01b94632-3ffe-11e7-94b9-0112eec1b081.PNG)

**Comment by Arcanemagus** [comment]
Without the information in the Console that the message is pointing you towards I can't really help you as I have no idea what could potentially be wrong here.

**Comment by chen0213sun** [comment]
Sorry for incomplete information. I have found the key to this error, it is setTimeout() methods. Error occurred only when setTimeout() in my codes. 
![default](https://cloud.githubusercontent.com/assets/23097255/26384726/c206cd8c-406d-11e7-818d-48ae6f9274c7.PNG)

**Comment by Arcanemagus** [comment]
The crash is inside the `json.js` file of `jshint` itself, not part of this package. Usually this happens when there is an invalid `.jshintrc` file, but generally there is more to the stack trace in that case.

What happens if you run `jshint` in the CLI on that file?

**Comment by chen0213sun** [comment]
I can't understand how to run jshint in the CLI on that file. sorry.....

**Comment by chen0213sun** [comment]
I am sorry to disappoint you. I don't understand how to run `jshint` in the CLI. So is it all right on other users? I try to test `setTimeout()`on another PC, same error occurred.

**Comment by Arcanemagus** [comment]
Sorry, it looks like this is actually a bug in the JSON reporter used to make JSHint output usable, and has already been filed as https://github.com/sindresorhus/jshint-json/issues/1.
