### ISSUE TITLE
Inline JavaScript is not working

### ISSUE THREAD

**Issue by jarrodek** [AtomLinter/linter-jshint#411]
The inline JavaScript option  is not working and I needed to set additional scope of `source.js.embedded.html` so the linter started working.

It happened under Ubuntu and latest Mac.

An example `web-components.html` file:

```html
<link rel="import" href="../element.html">
<custom-element>
  <!-- HTML content -->
  <script>
     // It is not working here
  </script>
</custom-element>
```

Logged cursor output when focusing on a function body in the script block:
- text.html.basic
- source.js.embedded.html
- meta.function-call.js
- meta.arguments.js

**Comment by Arcanemagus** [comment]
That's exactly the same scope as is [currently used](https://github.com/AtomLinter/linter-jshint/blob/v3.1.2/lib/main.js#L49), so adding that explicitely shouldn't do anything.

Without manually adding that can you run Linter's diagnostic command from the Command Palette?

**Comment by jarrodek** [comment]
```json
Atom version: 1.17.2
linter-jshint version: 3.1.2
JSHint version: jshint v2.9.4
Hours since last Atom restart: 2.7
Platform: darwin
Current file's scopes: [
  "text.html.basic",
  "source.js.embedded.html",
  "meta.function-call.js",
  "meta.arguments.js",
  "meta.brace.curly.js"
]
linter-jshint configuration: {
  "lintInlineJavaScript": true,
  "executablePath": "",
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

So I can see that `source.js.embedded.html` is on the list. For last few weeks I had problems with liner and finally today I had a time to take a look what is happening. After adding `source.js.embedded.html` to scopes it started working as it should. I'm confused here and I don't know what is happening.

**Comment by Arcanemagus** [comment]
Can you run `Linter: Debug` as well?

**Comment by Arcanemagus** [comment]
Just tried to reproduce this and everything seems to be working perfectly fine for me. If you are still having issues please provide the requested information. Make sure your cursor is within the embedded script section so the `source.js.embedded.html` scope is active.

**Comment by andrericardo** [comment]
Same issue here, linter works on script.js but not inline.

```
Atom version: 1.23.1
linter-jshint version: v3.1.6
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.1
Platform: darwin
Current file's scopes: [
  "text.html.basic",
  "meta.tag.script.html",
  "source.js.embedded.html",
  "punctuation.definition.tag.html"
]
linter-jshint configuration: {
  "lintInlineJavaScript": true,
  "executablePath": "",
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment]
@andrericardo You've missed the critical step of adding `source.js.embedded.html` to the "Scopes" setting, note how Linter's debug shows you have no matching providers for the file.

**Comment by andrericardo** [comment]
Thank you @Arcanemagus, adding `source.js.embedded.html` to the "Scopes" did fix it! Now have linting in inline <script> tags.
