### ISSUE TITLE
Broken: Disable When No Jshintrc File In Path

### ISSUE THREAD

**Issue by binarykitchen** [AtomLinter/linter-jshint#412]
Does not seem to have an impact. When ticked, it still lints. Using v3.1.2 here on latest atom.

See screenshot for settings. On the left, you see the file contents of my branch and that `gulpfile.babel.js` is yellow-underlined as erroneous by your linter. Any clues?

![selection_004](https://user-images.githubusercontent.com/177641/27121384-31ad4df4-513b-11e7-9ab9-af7fafef0aee.png)

**Comment by Arcanemagus** [comment]
I'm guessing that you have a `.jshintrc` file in some _parent_ directory, you can check what it is finding by placing a breakpoint [here](https://github.com/AtomLinter/linter-jshint/blob/v3.1.2/lib/main.js#L125) in the developer tools.

**Comment by binarykitchen** [comment]
oh damn, very true. thanks for pointing to that. wish there was a visual indication somehwere saying it's a global one defining it.

**Comment by Arcanemagus** [comment]
Silently using it is the same behavior as the CLI version of `jshint` for better or worse. With ESLint you can put `"root": true` in the config to prevent further checking but I don't think JSHint ever adopted that.
