### ISSUE TITLE
Invalid position given by 'W030'

### ISSUE THREAD

**Issue by TotomInc** [AtomLinter/linter-jshint#421]
JSHint returned a point that did not exist in the document being edited.
Rule: `W030`
Requested start point: 18:78

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.4
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.1
Platform: win32
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js",
  "punctuation.definition.arguments.end.bracket.round.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment]
Is your file indented using tabs?

**Comment by TotomInc** [comment]
Yes, I always indent with tabs.

**Comment by Arcanemagus** [comment]
Please follow https://github.com/jshint/jshint/issues/3151 then as this is a known issue with JSHint being broken for almost everything when using tab indentation.

**Comment by Arcanemagus** [comment]
Reopening this as a tracking issue so future users that update to v3.1.5 will get directed here and see the related JSHint issue.

If anyone is directed here and _isn't_ using tabs to indent your file please file a new issue with a file to reproduce it on the JSHint repo, or file one here and I'll try to help you in getting one filed there where it can be fixed.

**Comment by surdu** [comment]
As far as I understanf, linter-jshint also provides the jshint tool. Couldn't you guys roll back to an older version until thy sort their stuff out ? Those messages are really annoying 😞

**Comment by Arcanemagus** [comment]
@surdu Do you know when this started breaking on their end? I'm not going to roll back the version here in the package, but it would be interesting to know when it broke. If you want to change the version you are using locally you can point the package at a different version in the settings.

The reason this only started showing up recently here is that the thing that was _supposed_ to be showing them was broken due to a [silly mistake](https://github.com/AtomLinter/linter-jshint/pull/417) here.

**Comment by surdu** [comment]
Well it strarted showing up just after your last update, but I didn't know is was not showing up before due to a bug in this package.

I'm not going to roll back the version eighter. I'll wait it our for a few days and switch to another linter if it will still be there.

**Comment by Arcanemagus** [comment]
I would _highly_ recommend ESLint, it's a far better linter than JSHint.

**Comment by Arcanemagus** [comment]
There are reports that if you set your `indent` property of your JSHint configuration to `1` this issue can be worked around. If you don't have a `.jshintrc` file the following should work:
```json
{
  "indent": 1
}
```

**Comment by Arcanemagus** [comment]
@TotomInc I'm keeping this open as a tracking issue since the package will search for an open issue before attempting to file a new one. If you would no longer like to receive notifications from this thread please click "Unsubscribe" on the right, thanks again for filing this!

**Comment by TotomInc** [comment]
Sorry for closing the issue, I thought it was resolved and you (and I) forgot to close it.

**Comment by Arcanemagus** [comment]
Nope, 8 months later and JSHint still can't handle tabs 😆.
