### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by marosca** [AtomLinter/linter-jshint#433]
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested start point: 8:6

$(function(){
	$('#boton').on('mouseover',function(){
		$('body').css('background-color', 'black');
	});

	$('#boton').on('mouseleave',function(){
		$('body').css('background-color', 'white');
	})
});

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.4
JSHint version: jshint v2.9.5
Hours since last Atom restart: 1.1
Platform: darwin
Current file's scopes: [
  "source.js",
  "punctuation.terminator.statement.js"
]
linter-jshint configuration: {
  "lintInlineJavaScript": true,
  "executablePath": "",
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment]
Since your example code is indented using tabs, you are hitting a bug in JSHint where almost (?) all rules are broken when using tabs. Please follow https://github.com/jshint/jshint/issues/3151 for further updates on getting this fixed in JSHint.
