### ISSUE TITLE
Invalid position given by 'W002'

### ISSUE THREAD

**Issue by kimamil** [AtomLinter/linter-jshint#449]
JSHint returned a point that did not exist in the document being edited.
Rule: `W002`
Requested point: 33:23

`if (story.lastTime != story.time) {
				try{
					story.popQueue();
				}
				catch(e){
					this.log(e);
				}
            }`

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 1.5
Platform: darwin
Current file's scopes: [
  "source.js",
  "punctuation.terminator.statement.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment]
Hmmm, I'm unable to replicate this with the default configuration with the text provided. Can you provide your full JSHint configuration, and make sure that _just_ the text above replicates the issue?

**Comment by kimamil** [comment]
How do I provide the full config?

It definitely is the try...catch, but it is implemented in a function. I'am not eager to send you my full function ;)

**Comment by Arcanemagus** [comment]
By that I mean your `.jshintrc` file.

And when I place _just_ the text you provided in a file, I don't see it currently, but it might be related to some option you have enabled/disabled in your JSHint configuration.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response. Please provide the requested information when you get a chance so this can be investigated further 😉.
