### ISSUE TITLE
Linter does not check files ignored by Git

### ISSUE THREAD

**Issue by borisovg** [AtomLinter/linter-jshint#450]
If a file is inside a directory that is ignored by Git then no linting is done.

Compare

<img width="387" alt="screenshot1" src="https://user-images.githubusercontent.com/3171327/27790713-9c7a1556-5fe9-11e7-80de-073c4eeff433.png">

with

<img width="387" alt="screenshot2" src="https://user-images.githubusercontent.com/3171327/27790716-a4316f38-5fe9-11e7-8572-de1f12f5c1ae.png">

Atom    : 1.18.0
Plugin  : 3.1.5

**Comment by Arcanemagus** [comment]
This is expected behavior. `linter` (which runs this package) follows the setting in Atom itself of "Exclude VCS Ignored files", if you _really_ want to lint ignored files you will need to disable that setting.
