### ISSUE TITLE
Invalid position given by 'E030', 'E033', & 'E058'

### ISSUE THREAD

**Issue by AJMaxwell** [AtomLinter/linter-jshint#473]
JSHint returned a point that did not exist in the document being edited.
Rule: `E030`
Requested point: 19:44

Rule: `E033`
Requested point: 18:42

Rule: `E058`
Requested point: 18:43

Debug information:
```
Atom version: 1.19.0-beta4
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 4.4
Platform: linux
Current file's scopes: [
  "source.js",
  "meta.import.js",
  "string.quoted.single.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

The file that throws these errors (tab indented):
```
import api from '@/api/auth'

const state = {
	user: {},
	roles: [],
	permissions: []
}

const getters = {
	getAuth: state => state.user,
	getRoles: state => state.roles,
	getPermissions: state => state.permissions
}

const actions = {

	async setAuth ({ commit }) {
		const payload = (await api.auth()).data
		commit('setAuth', await payload.user)
	},

	async setRoles ({ commit }) {
		const payload = (await api.roles()).data
		commit('setRoles', await payload.roles)
	},

	async setPermissions ({ commit }) {
		const payload = (await api.permissions()).data
		commit('setPermissions', await payload.permissions)
	}

}

const mutations = {
	setAuth: (state, payload) => { state.auth = payload },
	setRoles: (state, payload) => { state.roles = payload },
	setPermissions: (state, payload) => { state.permissions = payload }
}

export default {
	namespaced: true,
	state,
	getters,
	actions,
	mutations
}
```
This same file also throws [E020](https://github.com/AtomLinter/linter-jshint/issues/465) and [E041](https://github.com/AtomLinter/linter-jshint/issues/464)

**Comment by Arcanemagus** [comment]
Are JSHint rules only numerically indexed and it's just prefixing them with the level (that you have changed to error)? Those numbers match other common reports.

In any case, this is almost certainly another case of https://github.com/jshint/jshint/issues/3151.

**Comment by Arcanemagus** [comment]
I'm going to close this since:
* There is nothing that can be done about this in this package, the bug is in JSHint
* Your title isn't one that would be generated by the package, so the "auto-find existing issue" won't find it

Thanks for taking the time to report this and please follow that JSHint issue for the progress on getting this resolved. Unfortunately since this is all part of the style rules which they want to remove anyway it doesn't seem like they are very interested in fixing this. I'd recommend just switching to ESLint which is a _far_ better linter in the first place. 😛

**Comment by AJMaxwell** [comment]
I am running ESLint during my build process and it doesn't have any problems with it. I'll switch to [`linter-eslint`](https://github.com/AtomLinter/linter-eslint) in Atom.

Thanks for all your help!
