### ISSUE TITLE
Setting for validate on save only

### ISSUE THREAD

**Issue by hadiwina** [AtomLinter/linter-jshint#489]
Hi,

This is more of a question as I'm not sure where or how to set it properly. Is it possible to get the linter only lint JS files on save rather than validating continuously?

**Comment by Arcanemagus** [comment]
If you go into the settings for the `Linter` package and disable "Lint on change" then providers will only be triggered on save 😉.

**Comment by hadiwina** [comment]
Thanks @Arcanemagus for the prompt reply!

I can't seem to see this in my setting. I wonder if I have an older version or something. However, there doesn't seem a prompt to update the package at all.

<img width="729" alt="screen shot 2017-08-23 at 3 40 23 pm" src="https://user-images.githubusercontent.com/5366783/29635045-ce336360-8819-11e7-828f-4ff27dddd7b2.png">

**Comment by Arcanemagus** [comment]
The `linter` package, not `linter-jshint`.

`linter` is the package that handles running all the different providers you have installed, aggregating their messages, and sending them on to a UI (`linter-ui-default`) to be shown to you.

`linter-jshint` is just one of the many available providers that provide a service allowing `linter` to request messages about a particular file.

**Comment by hadiwina** [comment]
Oh my! That makes a lot of sense now. 
Thank you very much for the help @Arcanemagus 🥇
