### ISSUE TITLE
JSHint is showing errors in HTML files (not in scripts)

### ISSUE THREAD

**Issue by callumlocke** [AtomLinter/linter-jshint#49]
![image](https://cloud.githubusercontent.com/assets/250617/6110436/7f87bd08-b079-11e4-9a2d-e01aa457fd34.png)

**Comment by callumlocke** [comment]
it seems that if the first non-whitespace character is **not** a `<`, then linter-jshint decides the entire HTML file is in fact a JS file.

obviously my screenshot shows a badly formed HTML document, but...

1. the HTML5 spec explicitly allows this

2. if you're working with HTML template partials that start with something like `{% extends 'layout' %}` then you don't really have a choice

**Comment by callumlocke** [comment]
it looks like you're using the [`--extract=auto`](http://jshint.com/docs/cli/) flag, which seems to try to detect if it 'looks like' an HTML file, and if it doesn't (because it doesn't start with a `<`), it just treats the entire file as JS.

it would be better to set this flat to `always` for HTML, and `never` for JS... but it looks like [linter](https://github.com/AtomLinter/Linter) doesn't allow setting the command flags dynamically per filetype..?

**Comment by steelbrain** [comment]
Fixed
