### ISSUE TITLE
Error: Cannot find module 'C:\path\to\bundled\jshint'

### ISSUE THREAD

**Issue by VladTzaru** [AtomLinter/linter-jshint#504]
Hi, this is the error I get when I try to run the plug-in. I am guessing this is related to the path, but I am not sure how to fix it. Any help is highly appreciated.

```
[Linter] Error running JSHint Error: module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\path\to\bundled\jshint'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:424:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:544:3

    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:424:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:544:3
    at ChildProcess.<anonymous> (C:\Users\Tzaru\.atom\packages\linter-jscs\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
(anonymous) @ linter-registry.js:137
_tickCallback @ internal/process/next_tick.js:103
```
Thank you in advance.

**Comment by Arcanemagus** [comment]
Is it _literally_ saying `'C:\path\to\bundled\jshint'` or were you trying to anonymize the path? (you missed the latter path if so.)

**Comment by Arcanemagus** [comment]
As for your actual problem, the only way I can think for this to happen is if Atom failed to properly install the dependencies, can you try re-installing the package?

**Comment by VladTzaru** [comment]
Hey @Arcanemagus, first of all, thanks for your time. I did try to reinstall it, a couple of times actually, the path always remains the same.

**Comment by Arcanemagus** [comment]
Did you try editing your settings manually instead of using the Settings page? The _only_ place that text appears is in the [settings example](https://github.com/AtomLinter/linter-jshint#settings) in the README.

**Comment by VladTzaru** [comment]
When I leave it empty, nothing happens, no error, but it's not scanning the file either. I'll poke around, not sure should I play with the config file at all?

**Comment by Arcanemagus** [comment]
Generally no, it should work with no configuration of the package.

You can check the raw output coming from JSHint by placing a breakpoint in Atom's Developer Tools here:
https://github.com/AtomLinter/linter-jshint/blob/39e20b65e69ce2839a3cb87c3e0a47dcff999fbb/lib/main.js#L161

**Comment by VladTzaru** [comment]
Will do, thanks. I will let you know once I figure it out.

**Comment by Arcanemagus** [comment]
If you aren't familiar with Developer Tools, here's a mini-tutorial: https://github.com/AtomLinter/linter-clang/issues/220#issuecomment-326346796

**Comment by Arcanemagus** [comment]
Are you still having issues @VladTzaru?

**Comment by VladTzaru** [comment]
@Arcanemagus Hey, sorry for the delayed response, I was quite busy. I've reinstalled everything, including Atom, seems to be working now. I'm still not sure what exactly happened. :) In any case, all is good now. Thank you for your time.
