### ISSUE TITLE
Error running JSHint Error: Failed to spawn command `C:\WINDOWS\system32\cmd.exe`

### ISSUE THREAD

**Issue by rosseg** [AtomLinter/linter-jshint#547]
Make sure `C:\WINDOWS\system32\cmd.exe` is installed and on your PATH
    at C:\Users\rossg\.atom\packages\linter-jscs\node_modules\atom-linter\lib\helpers.js:130:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

I added that to my path but cmd is in a different directory... any way to change where it looks for cmd?

**Comment by Arcanemagus** [comment]
What version of Windows are you on?

**Comment by rosseg** [comment]
I'm running Windows 10.

I think it was an error caused by git bash installing a wrapper to the PATH
variable. After uninstalling git, jscs, and jshint, then reinstalling jscs,
jshint, and git, but without the PATH wrapper, the error no longer appears.

**Comment by Arcanemagus** [comment]
Even that's strange, because that path is hard coded (it's been the same since Win2k or so?). In any case I'm glad you got it figured out!
