### ISSUE TITLE
It just wont Work

### ISSUE THREAD

**Issue by alexdancer** [AtomLinter/linter-jshint#557]
I constantly install linter-jshint and more by AtomLinter but it will not work. Is there a certain way I have to change the settings or settings with or computer. Or do I have to do it manually .If I do how to do it manually. Same thing with the html hint and scss hint.[ https://atom.io/packages/linter-jshint](url)

**Comment by Arcanemagus** [comment]
Do you have `linter` + `linter-ui-default` installed and enabled? Or alternatively `atom-ide-ui`?

These are just providers of a common service, you need something to actually _do_ something with the service.

**Comment by alexdancer** [comment]
Good know thanks

**Comment by alexdancer** [comment]
And I had to use ESlint and install that with my console it was not that

**Comment by Arcanemagus** [comment]
Are you still having issues? You didn't answer my earlier questions and I'm not actually sure what you mean by this:
> And I had to use ESlint and install that with my console it was not that

**Comment by alexdancer** [comment]
Just don't worry everything is good.
