### ISSUE TITLE
Add Support for Extended .jshintrc Files

### ISSUE THREAD

**Issue by domrein** [AtomLinter/linter-jshint#61]
I have two .jshintrc files. One in the root of the project, the other in a test directory which simply adds mocha globals. When using jshint from the command line, the test folder passing jshint with no errors. But in Atom, linter-jshint does not respect the values in the extended file and displays errors.

/.jshintrc
{
  "esnext": true,
  "camelcase": true,
  "curly": true,
  "globalstrict": true,
  "strict": true,
  "node": true
}

/src/test/.jshintrc
{
  "extends": "../../.jshintrc",
  "mocha": true
}

**Comment by halleycarleton** [comment]
+1 I'm running into the same exact situation right now. My `.jshintrc` for my test suite has no effect in Atom. Atom seems to only read the one in the project root.

**Comment by steelbrain** [comment]
We have now put the rc handling to jshint itself, so this one should be fixed.
