### ISSUE TITLE
Add file references to identify global variables and functions

### ISSUE THREAD

**Issue by PD75** [AtomLinter/linter-jshint#63]
I found that there are a lot of questions on this topic so I was surprised not to find the question here:

If I code in multiple files, I would need to add all global variables and function used between the files in the config file. This adds an extra mode of failure, since the names need to be maintained in two places. 

Visual studio uses  file reference/// <reference path="../dist/Semantic-UI-1.10.4/semantic.js" />. Something similar would make it more useful.

**Comment by steelbrain** [comment]
That's something that should be raised in `jshint`, not it's linter provider :)
