### ISSUE TITLE
Dead code after return not detected if function precedes

### ISSUE THREAD

**Issue by MilesBHuff** [AtomLinter/linter-jshint#638]
This gives an error, as expected:
`return foo;`
`console.log('Unreachable code'); // Error`
`function foo() {}`

This does not give an error:
`return foo;`
`function foo() {}`
`console.log('Unreachable code'); //No error`

This is probably an upstream issue, because I'm seeing the same problem in NPM with jshint v2.9.1;  but because I'm seeing the issue in Atom with linter-jshint, I'm also reporting it here.
Link to upstream issue:  https://github.com/jshint/jshint/issues/3330

**Comment by Arcanemagus** [comment]
This is just a wrapper around JSHint, you'll want to follow the issue you filed there for when this will be fixed.

Glad you found the right place to file this! 😉
