### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by rabugento** [AtomLinter/linter-jshint#66]
Hi, please help me to fix this issue. 
Thanks.

Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:267:11)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:14)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:223:30)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
```

**Comment by d4k0** [comment]
I just created a pull request with the needed changes: https://github.com/AtomLinter/linter-jshint/pull/71

**Comment by Arcanemagus** [comment]
Duplicate of #59.
