### ISSUE TITLE
"E058 - Missing semicolon" after await

### ISSUE THREAD

**Issue by keirwilliams** [AtomLinter/linter-jshint#740]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/26045249/58027936-98d0ec00-7b11-11e9-9163-f5a3efd3dae1.png">

linter-jshint is suggesting a semicolon after await. Which would break the code.

**Comment by Arcanemagus** [comment]
You should file this on the [JSHint repository](https://github.com/jshint/jshint), this package is just a wrapper around that.
