### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by dr00t** [AtomLinter/linter-jshint#78]
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:790:9)
Package.hasActivationCommands (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:715:20)
<unknown> (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:169:24)
Package.measure (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
```

**Comment by davivcgarcia** [comment]
This issue can be solved changing the **package.json** from **lint-jshint** plugin. If you are using a Linux/Mac system, the plugin should be installed at your home directory, as *~/.atom/packages/linter-jshint/package.json*. Change the **activationEvents** by **activationCommands** and reload the Atom.

**Comment by iam4x** [comment]
dup #70

**Comment by Arcanemagus** [comment]
Duplicate of #60.
