### ISSUE TITLE
No support for Template Strings

### ISSUE THREAD

**Issue by RyanWhite04** [AtomLinter/linter-jshint#92]
Part of the ECMAScript 6 (Harmony) proposal is string interpolation in Javascript.
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings

var myName = "ryan";
var templateString = `My name is ${myName}.`;

I'm not great at javascript so I don't know how to do this myself and I would probably just make it worse, but an option to allow this syntax would be nice.

**Comment by mafredri** [comment]
This is just a linter for jshint, if you wish to enable ES6 features in jshint, you must enable the esnext option: http://jshint.com/docs/options/#esnext. Even then I'm unsure if jshint has support for template strings, if not you can always check out eslint instead.

**Comment by hhsnopek** [comment]
:+1: - this should be documented within the README for reference (mainly just the `.jshintrc`)

**Comment by iam4x** [comment]
If you work with ES6/7 with babeljs, I recommend to use eslint with babel-eslint instead of jshint.

**Comment by hhsnopek** [comment]
@iam4x is there atom support?

**Comment by iam4x** [comment]
https://atom.io/packages/linter-eslint

**Comment by steelbrain** [comment]
Closed as it should be raised in `jshint` instead of it's linter provider.
