### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-jshint#96]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by steelbrain** [comment]
Done
